### ISSUE TITLE
[1.16.2] Book item model rendering issue

### ISSUE THREAD

**Issue by stfwi** [VazkiiMods/Patchouli#299]
Hi Vazkii, willie, I saw on the 1.16.2 port the effect that the book item models of my mods are not shown anymore (pink-black test block instead). The log does not show any error or exception, so my first impression from a quick peek into the code is that `PatchouliItems::replaceModel()` may not get invoked anymore (presuming that we would see an error if the special model registration of the book would not be done), or that model baking somehow results in a test-block model now.

- Versions: Patchouli 1.16-42 / Forge 33.0.22
- Book data: https://github.com/stfwi/engineers-decor/blob/1.16/src/main/resources/data/engineersdecor/patchouli_books/engineersdecor_manual/book.json

Cheers, and thanks for creating/maintaining the mod!

**Comment by williewillus** [comment]
do you have a log anyways? maybe there is something we can find there

**Comment by stfwi** [comment]
For additional data I also checked with Forge 33.0.20 and collected the logs and a screenshot. It's only the item model (all entries, recipes, pages etc are fine, the book data did not change since 1.16.1):

[2020-08-28-logs-patchouli-issue299.zip](https://github.com/Vazkii/Patchouli/files/5140897/2020-08-28-logs-patchouli-issue299.zip)

Cheers, -

**Comment by kd8lvt** [comment]
I'm also having a similar issue in 1.16.1 when using Patchouli as a modpack-maker (JSON files). The book's contents load fine, but the item model, in particular, seems to be erroring silently.
Forge version 32.0.108
Patchouli Version 1.16-39
[Book Data and Mod List](https://gist.github.com/kd8lvt/c0c3ecc80886afbca8661dd78887e693)
[Logs](https://github.com/Vazkii/Patchouli/files/5169354/2020-09-03-7.log.gz)

**Comment by jblaiseg** [comment]
This issue is present in all builds of forge/patchoulu for minecraft-1.16.3

**Comment by Lothrazar** [comment]
Same thing happens in my attempt to make a book.  Seems intermittent, maybe 1 in 10 tries it does load my item model/texture correctly, other times nothing. no errors in latest.log or debug.log.

https://github.com/Lothrazar/Cyclic/blob/trunk/1.16/src/main/resources/data/cyclic/patchouli_books/cyclic/book.json

temporarily i have it loading a default model As soon as i change 
  "model": "patchouli:book_purple",
into 
  "model": "cyclic:guide_book", 
i get exactly this issue

**Comment by Ellpeck** [comment]
I can confirm that this issue happens on Patchouli 44, both with just Nature's Aura and just Ars Noveau installed.

Additionally, this issue seems to be related to a race condition, as it seems to occur more often in bigger modpacks and for people with lower-end computers.

**Comment by williewillus** [comment]
I think we fixed the race conditions after a lot of bug hunting
