### ISSUE TITLE
shift right clicking onion crop with Patchouli book from "Crock Pot" mod causes crash

### ISSUE THREAD

**Issue by ianm1647** [VazkiiMods/Patchouli#374]
i don't know if it applies to any other crop in the mod either, all i know is that shift right clicking with the book causes the game to crash. crash report is below for you to decide yourself 

it may not be either one of these mods at all, but when i read the report the only mod that popped up while reading it was patchouli

[crash-2021-03-12_18.31.18-client.txt](https://github.com/Vazkii/Patchouli/files/6133767/crash-2021-03-12_18.31.18-client.txt)

**Comment by SeraphJACK** [comment]
After some investigation, I think this might be a patchouli bug. Details here:

https://github.com/Vazkii/Patchouli/blob/21a19855a9b45a1c311c053dcc448364d8c870af/src/main/java/vazkii/patchouli/client/book/BookContents.java#L277-L282

The onion entry has 2 pages, and the onion recipe appears on page 2, so it calculates the spread to be 1, which is wrong.

![image](https://user-images.githubusercontent.com/25274081/111023418-f4b9e280-8413-11eb-8889-93d83ec12c48.png)

When rendering, both the left page and right page are null, which eventually arises NPE.

**Comment by SeraphJACK** [comment]
I think change BookContents.java#L281 to 

```java
int spread = (page - 1) / 2; 
```

might fix the problem.

**Comment by SeraphJACK** [comment]
https://github.com/Vazkii/Patchouli/blob/21a19855a9b45a1c311c053dcc448364d8c870af/src/main/java/vazkii/patchouli/client/handler/BookRightClickHandler.java#L84

I guess this shouldn't be multiplied by 2?

**Comment by SeraphJACK** [comment]
This issue still exists, any idea?

**Comment by williewillus** [comment]
I read the code a bit more and I'm pretty sure what's there is correct (at least in latest 1.18). If it were broken a lot of other books would crash. Can anyone reproduce this on latest 1.18?
