### ISSUE TITLE
Crash when shift-clicking the a certain block with the book to open its page 

### ISSUE THREAD

**Issue by aaronhowser1** [VazkiiMods/Patchouli#389]
TeamPneumatic/pnc-repressurized/issues/798

https://pastebin.com/QeEcwgkn

**Minecraft Version**
1.16.5
**Forge Version**
36.1.4
**Mod Version**
Patchouli-1.16.4-50

**Comment by aaronhowser1** [comment]
A comment left on the linked issue:

> Hard to see this as being anything other than a Patchouli bug...

> I can reproduce this in my dev environment, although the relevant line in the stacktrace (GuiBookEntry.java:97) doesn't properly match the decompiled source for the class I have in my dev environment (using Patchouli 1.16.4-48). Stepping through with a debugger shows the the GuiBookEntry object's leftPage and rightPage are both null at this point and Patchouli is assuming a non-null leftPage object.

> So this is on Patchouli.

**Comment by SeraphJACK** [comment]
Seems the same issue #374
