### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by ZestyBlaze** [VazkiiMods/Patchouli#424]
[crash-2021-07-07_20.28.37-client.txt](https://github.com/Vazkii/Patchouli/files/6779724/crash-2021-07-07_20.28.37-client.txt)

I got this error on startup with the mod installed, no clue what is causing it

**Comment by williewillus** [comment]
Your .minecraft/patchouli_data.json got corrupted, delete it.
In modern versions the mod is more robust to this.
