### ISSUE TITLE
[bug] mods can't access patchouli appearently

### ISSUE THREAD

**Issue by TobiPeterG** [VazkiiMods/Patchouli#439]
Hey there,

the game log contains a lot messages like `Failed to load croptopia:patchouli_books/guide/en_gb/entries/utensils/mortar_and_pestle.json. Switching to fallback` on 1.17.1 beta version of this mod.

I reported it to croptopia https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues/238, but they don't believe it's an error on their side.
The log file is attached

[latest.log](https://github.com/ExcessiveAmountsOfZombies/Croptopia/files/7111454/latest.log)

**Comment by williewillus** [comment]
Commented on the original issue, not a Patchouli bug.
