### ISSUE TITLE
Patchouli Issue: No Such Method

### ISSUE THREAD

**Issue by alexklann** [VazkiiMods/Patchouli#445]
When using Patchouli with MCreator in a dev environment, I get the following issue.

> java.lang.NoSuchMethodError: net.minecraft.item.Item$Properties.func_200917_a(I)Lnet/minecraft/item/Item$Properties;

Full traceback:
[crash-2021-09-18_15.36.40-fml.txt](https://github.com/VazkiiMods/Patchouli/files/7189971/crash-2021-09-18_15.36.40-fml.txt)

**Comment by Hubry** [comment]
Are you trying to somehow run it by just putting the mod into the mods folder? Because that's not gonna work, dev environments use different mappings at runtime. 

Edit your buildscript to add the dependency using `fg.deobf` instead.
