### ISSUE TITLE
Pressing U on brown wool to see uses in recipes crashes my game

### ISSUE THREAD

**Issue by FearAK** [VazkiiMods/Patchouli#447]
Pressing U on brown wool to see uses in recipes crashes my game

[crash-2021-10-04_19.24.08-client.txt](https://github.com/VazkiiMods/Patchouli/files/7280415/crash-2021-10-04_19.24.08-client.txt)

**Comment by Hubry** [comment]
There is absolutely nothing that leads this crash report to being Patchouli's fault. REI crashed while rendering a `mocolors:painter`.

**Comment by FearAK** [comment]
Oh, didn't realise that was the mod causing it. very sorry and thank you!
