### ISSUE TITLE
1.17 weird (I might just be stupid)

### ISSUE THREAD

**Issue by TheQuackMeister** [VazkiiMods/Patchouli#448]
So I downloaded patchouli for 1.17.1 fabric, and it didn't really work? I have only the guide book and it says "invalid book: no ID defined" in REI. I have no idea what went wrong or how to fix it.

These are the mods I currently have in case there's an incompatibility issue:
-farmer's delight (the reason I need patchouli)
-culinaire
-foodables
-mo glass
-complete bone meal
-xaeros minimap
-origins
-environmental armor
-roughly enough items
-dawn
-cloth config
-architectury

**Comment by williewillus** [comment]
Patchouli provides no content on its own, it's just a library that other mods can use to make their books. You'll want to look at the content mods you have to see if any of them have a recipe you can use to obtain their book.

**Comment by williewillus** [comment]
^
