### ISSUE TITLE
So there's no way to hot reload and apply changes to the book

### ISSUE THREAD

**Issue by ChromaPIE** [VazkiiMods/Patchouli#453]
According to 1.17 Upgrade Guide, books can be overridden by resourcepacks when use_resource_pack is true. I did that directly to the jar, and tried Open Loader firstly, failed, as _expected_, then made a resourcepack zip, unfortunately it didn't work either. I also tried loading it in data way through Open Loader too, not working. So I am wondering that, will vanilla datapack work? If not how is it DATA-DRIVEN?

Sorry to be aggresive but Patchouli sucks at it since it leaves 1.12.

**Comment by williewillus** [comment]
1. Every single time you say the words "failed" or "didn't work", there are zero details to follow up on it with. How are we supposed to help you debug if you don't provide any information?
2. > Sorry to be aggresive

I'm sorry to say, Patchouli is developed by me and a couple other people on our entire (vanishing) free time. There are lots of other things that we *could* be doing instead. So being aggressive then "apologizing" for it achieves nothing but make me want to work on it less.

Hop on Discord #patchouli channel and ask. It might be more helpful to chat live.

**Comment by ChromaPIE** [comment]
Okay so let's make it quick and clean with several questions:
For Patchouli fabric 1.17.1,
- Is it a must to specify `use_resource_pack: true` in book.json to allow resourcepacks to override the books? If so does that mean that you must edit the jar itself to make any changes to the book? If so what modpack creators and resourcepack-based localization project contributor can do to edit, override or extend the book content? 
- Shift right clicking the pen icon reloads the book. Now it's tested that after switching between languages the book requires a reload to apply contents for the current language. Excluding this, what else can this feature do? In Patchouli 1.12 we can copy and paste everything into the resources folder, created by ResourceLoader mod, edit or add something, and reload the book to see changes real time, all with ease, but nowadays it's no longer possible, or is it?
