### ISSUE TITLE
How do you hotload books?

### ISSUE THREAD

**Issue by JadianRadiator** [VazkiiMods/Patchouli#455]
[Everything after this can be hot loaded without closing the game, so feel free to keep it open as you do further edits.](https://vazkiimods.github.io/Patchouli/docs/patchouli-basics/getting-started#4-check-ingame)

Then how do you hotload books?
Because that page doesn't say how,
and my book hasn't loaded in.
Not even after using the /reload command.

Here's the modpack author book folder and the CraftTweaker script used to add the book to jei.
[City Economics.zip](https://github.com/VazkiiMods/Patchouli/files/7427421/City.Economics.zip)

**Comment by Hubry** [comment]
> Save your files, then return ingame and open your book. Shift-click the pencil in the bottom-left corner. When you do so, it will reload the book contents, and you should see the category and entry you just defined appear.

Directly from that page. Did you make the book *after* loading the game? Books are created on game load, you need to restart the game to edit book.json.

**Comment by JadianRadiator** [comment]
the page didn't make that specification

**Comment by williewillus** [comment]
"Everything after this"
