### ISSUE TITLE
Latest 1.17.1 Patchouli version crashing server

### ISSUE THREAD

**Issue by itsdinkd** [VazkiiMods/Patchouli#464]
---- Minecraft Crash Report ----
// Oops.

Time: 11/22/21, 11:43 PM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: vazkii/patchouli/common/network/message/MessageOpenBookGui
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.52)
	at vazkii.patchouli.common.base.PatchouliAPIImpl.openBookGUI(PatchouliAPIImpl.java:68)
	at vazkii.patchouli.common.item.ItemModBook.use(ItemModBook.java:161)
	at net.minecraft.item.ItemStack.use(ItemStack:254)
	at net.minecraft.server.network.ServerPlayerInteractionManager.interactItem(ServerPlayerInteractionManager:282)
	at net.minecraft.server.network.ServerPlayNetworkHandler.onPlayerInteractItem(ServerPlayNetworkHandler:1086)
	at net.minecraft.network.packet.c2s.play.PlayerInteractItemC2SPacket.apply(PlayerInteractItemC2SPacket:25)
	at net.minecraft.network.packet.c2s.play.PlayerInteractItemC2SPacket.apply(PlayerInteractItemC2SPacket:7)
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:21)
	at net.minecraft.server.ServerTask.run(ServerTask:18)
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:151)
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23)
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:788)
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:164)
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:125)
	at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer:770)
	at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:764)
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:110)
	at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer:748)
	at net.minecraft.server.MinecraftServer.handler$bip000$modifiedRunLoop(MinecraftServer:7399)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:270)
	at java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.ClassNotFoundException: vazkii.patchouli.common.network.message.MessageOpenBookGui
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.fabricmc.loader.impl.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:57)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 22 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Linux (amd64) version 5.10.0-9-amd64
	Java Version: 16.0.2, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 8412690616 bytes (8022 MiB) / 11274289152 bytes (10752 MiB) up to 11274289152 bytes (10752 MiB)
	CPUs: 5
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 5950X 16-Core Processor
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 16
	Number of logical CPUs: 32
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 159692.41
	Virtual memory used (MB): 151042.08
	Swap memory total (MB): 95301.00
	Swap memory used (MB): 56765.92
	JVM Flags: 21 total; -XX:+UseContainerSupport -Xms10750M -Xmx10750M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
	Fabric Mods: 
		addendum: Addendum 1.0.2
		adorn: Adorn 2.3.1+1.17.1
		advanced_runtime_resource_pack: Runtime Resource Pack 0.4.3
		adventure-platform-fabric: adventure-platform-fabric 4.1.0-SNAPSHOT
		adventurez: AdventureZ 1.4.3
		ae2wtlib: AE2WTLib 9.0.0-beta.8
		agape_space: Space Dimensions 0.3.5
		alloy_forgery: Alloy Forgery 2.0.6
		annotateddi: Annotated DI 2.0.4+1.17.1
		antishulkerdupe: Antishulkerdupe 1.0.0
		aopalliance_aopalliance: aopalliance 1.0
		apoli: Apoli 2.0.5
		appleskin: AppleSkin mc1.17.1-2.2.0
		appliedenergistics2: Applied Energistics 2 9.0.0-beta.2
		aqupdcaracal: Caracal mob 1.17-1.3.2
		arcanus: Arcanus 1.23
		architects_palette: Architect's Palette Fabric 1.3
		architectury: Architectury 2.6.35
		artifality: Artifality 0.4.3
		artifice: Artifice 0.15.3+21w07a
		attributefix: Attribute Fix {FABRIC} 1.0.3
		autoconfig1u: Auto Config v1 Updated 3.3.1
		badstdout: BadStdOut 1.1.0-1.17
		balm-fabric: Balm 1.8.0+0
		banhammer: BanHammer 0.4.1+1.17.1
		battletowers: Battle Towers 3.4.1-1.17.1
		bclib: BCLib 0.5.1
		beenfo: Beenfo 1.17.1-fabric0.36.1-1.3.2
		betterdungeons: YUNG's Better Dungeons 1.17-1.0.2
		betterend: Better End 0.12.2
		bettermineshafts: YUNG's Better Mineshafts 1.17-1.0.1
		betternether: Better Nether 5.3.11
		betterstrongholds: YUNG's Better Strongholds 1.17-1.1.2
		bewitchment: Bewitchment 1.17-14
		bfapi: BFAPI 1.1.10
		bitsandchisels: BitsAndChisels 2.5.4
		blame: Blame 1.17-4.3.0-fabric
		blockbot-api: BlockBot Api 1.0.0
		blockbot-discord: BlockBot Discord 2.0.0-beta
		blockshifter: Blockshifter 1.4.0+fabric-1.17.1
		blockus: Blockus 2.2.10+1.17.1
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.3.2-1.17.1
		bountiful: Bountiful 1.0.0
		box-of-placeholders: Box of Placeholders 1.3.2+1.17.1
		buildinggadgets: st'ructure tools 1.0.5
		calio: Calio 1.3.0
		cardinal-components: Cardinal Components API 3.1.1
		cardinal-components-base: Cardinal Components API (base) 3.1.1
		cardinal-components-block: Cardinal Components API (blocks) 3.1.1
		cardinal-components-chunk: Cardinal Components API (chunks) 3.1.1
		cardinal-components-entity: Cardinal Components API (entities) 3.1.1
		cardinal-components-item: Cardinal Components API (items) 3.1.1
		cardinal-components-level: Cardinal Components API (world saves) 3.1.1
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 3.1.1
		cardinal-components-util: Cardinal Components API (utilities) 3.1.1
		cardinal-components-world: Cardinal Components API (worlds) 3.1.1
		carpet: Carpet Mod 1.4.52
		carpet-extra: Carpet Extra 1.4.51
		carpet-fixes: Carpet Fixes 1.17.1-1.2.0+v211021
		carpet-tis-addition: Carpet TIS Addition 1.24.0+build.742
		carrier: Carrier 1.8.2
		chalk: Chalk 1.0.2
		charm: Charm 3.3.2
		chunky: Chunky 1.2.197+ishlandfork
		clean-logs: Clean Logs 1.0.1
		cloth-api: Cloth API 2.0.54
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config-lite: cloth-config-lite 2.0.6
		cloth-config2: Cloth Config v5 5.1.40
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		cloud: Cloud 1.5.0
		cloud_commandframework_cloud-brigadier_: cloud-brigadier 1.5.0
		cloud_commandframework_cloud-core_: cloud-core 1.5.0
		cloud_commandframework_cloud-minecraft-extras: cloud-minecraft-extras 1.5.0
		cloud_commandframework_cloud-services_: cloud-services 1.5.0
		cmdspy: Command Spy 1.2.3
		collective-fabric: Collective (Fabric) 1.62
		colorutility: ColorUtility 2.0.1
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		com_fasterxml_jackson_dataformat_jackson-dataformat-yaml: jackson-dataformat-yaml 2.12.2
		com_flowpowered_flow-math: flow-math 1.0.3
		com_github_dimensionaldevelopment_poly2tri_java: poly2tri.java 0.1.1
		com_google_inject_guice: guice 5.0.1
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_typesafe_config: config 1.4.1
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		companion_bats: Companion Bats 1.18.4
		compress: Compress 'em [v1.5]
		conjuring: Conjuring 1.0.15
		consistency_plus: Consistency Plus 0.4.1+1.17
		cosmetic-armor: Cosmetic Armor 1.1.0
		craftingtweaks: Crafting Tweaks 13.1.0+0
		creativeonepunch: Creative One-Punch 1.2
		crookedcrooks: Crooked Crooks 2.0.1+1.17.1
		croparia: Croapria 1.17.1-0.0.4
		croptopia: Croptopia 1.6.3
		croptosis: Croptosis 1.2.0
		crowdin-translate: CrowdinTranslate 1.3+1.17
		customspawns: Custom Spawns 0.5+1.17
		dark-enchanting: Dark Enchanting 0.4.1-1.17.1
		darkpaintings: Dark Paintings 4.0.2
		dataattributes: Data Attributes 1.0.6
		dimdoors: DimensionalDoors 4.0.0+beta.3-31.10.2021
		discerning_furnace: Discerning Furnace 1.0.3+MC1.17-1.17.1
		dml-refabricated: Deep Mob Learning: Refabricated 0.4.4-beta
		dml-refabricated-base: DML: Refabricated - Base 0.4.4-beta
		dml-refabricated-events: DML: Refabricated - Vanilla Events 0.4.4-beta
		dml-refabricated-modular-armor: DML: Refabricated - Glitch Armor 0.4.4-beta
		dml-refabricated-rei: DML: Refabricated - REI Integration 0.4.4-beta
		dmlsimulacrum: Deep Mob Learning: Simulacrum 1.0.5
		doom: Doom Fabric 4.0.32
		dragonloot: DragonLoot 1.0.9
		dual_riders: DualRiders 1.0.5
		dungeons_arise: When Dungeons Arise 2.1.48-fabric
		ec-core: Essential Commands Core 1.0.0-mc1.17.1
		eldritch_mobs: Eldritch Mobs 1.9.6
		emagnet: E Magnet 1.2.3
		enchant_giver: Enchant Giver 1.1.0
		essential_commands: Essential Commands 0.17.0-mc1.17.1
		essentialaddons: Essential Addons 1.17.1-1.0.6
		expandedstorage: Expanded Storage 7.2.7
		extraalchemy: Extra Alchemy 1.6.1
		extragenerators: Extra Generators 1.1-BETA+1.17
		extraorigins: Extra Origins 1.17-10
		fabric: Fabric API 0.42.1+1.17
		fabric-api-base: Fabric API Base 0.4.0+5847535018
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.1+5847535018
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.2+5847535018
		fabric-command-api-v1: Fabric Command API (v1) 1.1.4+5847535018
		fabric-commands-v0: Fabric Commands (v0) 0.2.3+5847535018
		fabric-containers-v0: Fabric Containers (v0) 0.1.13+5847535018
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.1+5847535018
		fabric-copper-golem: Copper Golem 1.0.1+1.17.1
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.6+5847535018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.13+5847535018
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.3.1+5847535018
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.11+5847535018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.2+5847535018
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.8+5847535018
		fabric-item-api-v1: Fabric Item API (v1) 1.2.5+5847535018
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.1+5847535018
		fabric-language-kotlin: Fabric Language Kotlin 1.6.5+kotlin.1.5.31
		fabric-language-scala: Fabric Language Scala 1.1.0+scala.2.13.6
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.5+5847535018
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.5+5847535018
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.2+6d0fac4218
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.5+6d0fac4218
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.14+5847535018
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.12+5847535018
		fabric-networking-v0: Fabric Networking (v0) 0.3.3+5847535018
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.11+6d0fac4218
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.5+6d0fac4218
		fabric-particles-v1: Fabric Particles (v1) 0.2.5+5847535018
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.13+5847535018
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.6+5847535018
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.2.1+6d0fac4218
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.9+5847535018
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.9+5847535018
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.14+5847535018
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.2+5847535018
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.1+eb76084f18
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.1+6d0fac4218
		fabricenchantments: Fabric Enchantments 0.5.0
		fabricloader: Fabric Loader 0.12.5
		fabricsit: FabricSit 1.6.4
		fabrictailor: Fabric Tailor 1.7.1
		factory: Factory 1.17.1-1.4.0
		fake-player-api: Fake Player API 0.2.0
		fallflyinglib: FallFlyingLib 3.0.0-beta.2
		fallingtree: FallingTree 2.14.3
		farmersdelight: Farmer's Delight 1.17.1-0.1.3
		fatxporbs: Fat Experience Orbs 1.0.1
		fermion: Fermion 2.11.241
		fermion-modkeys: Fermion Modifier Keys 1.10.241
		ferritecore: FerriteCore 3.1.0
		fiber: fiber 0.23.0-2
		fireplacelib: Fireplace Lib 6.1.0+1.17.1
		flan: Flan 1.17.1-1.6.3
		fluidtank: Fluid Tank 17.1.3-fabric
		flytre-lib-base: Flytre Lib - Base Module 1.3.0
		flytre-lib-compat: Flytre Lib - Compat Module 1.0.0
		flytre-lib-config: Flytre Lib - Config Module 1.1.0
		flytre-lib-event: Flytre Lib - Event Module 1.0.1
		flytre-lib-gui: Flytre Lib - GUI Module 1.0.0
		flytre-lib-storage: Flytre Lib - Storage Module 2.3.2
		flytre_lib: Flytre Lib 1.4.2
		geckolib3: Geckolib 3.0.26
		givemehats: Give Me Hats! 1.6.5
		glassdoor: Glass Doors 1.5.0-1.16
		glassential: Glassential 1.17-1.2.0
		go-fish: Go Fish 1.3.0-beta-1.17.1
		goat: Goat Origin 1.0.0
		gobber2: Gobber2 2.4.60
		goldenhoppers: Golden Hoppers 1.1.0
		golemsgalore: Golems Galore 1.0.3-1.17.1
		harvest_scythes: Harvest Scythes 2.1.0
		hctm-base: HCTM Base 3.6.2
		headindex: Head Index 1.0.3
		heartbond: Heartbond 1.1.0
		hologram-api: Hologram API 0.2.1+1.17.1
		hookshot: Hookshot 22.0
		horseinfo: Horse Info 0.3.0-1.17
		horsestonks: Horse Stonks 1.0.0
		hydrogen: Hydrogen 0.3
		impersonate: Impersonate 2.3.5
		improved-stations: Improved Stations 2.0.7
		incantationem: Incantationem 1.1.2+1.17.1
		indrev: Industrial Revolution 1.12.0-BETA
		inmis: Inmis 2.3.2-1.17.1
		invview: InvView 1.4.6-1.17.1+
		io_leangen_geantyref_geantyref: geantyref 1.3.11
		ironfurnaces: Iron Furnaces 1.17.1-2.7.1-fabric
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		javax_inject_javax_inject: javax.inject 1
		jline4mcdsrv: JLine for Minecraft Dedicated Server 0.2.0
		kambrik: Kambrik 1.1.0
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		kibe: Kibe 1.9.4-BETA+1.17
		kjsextras: KubeJS Extras 1.4.0
		krypton: Krypton 0.1.4
		ktdatataglib: KtDataTagLib 1.5.4
		kubejs: KubeJS 1701.3.10-build.9999
		lacrimis: Lacrimis 2.1.3+1.17.1
		lapisreserve: Lapis Reserve 1.0.8
		ledger: Ledger 1.1.1+build.402
		libblockattributes: LibBlockAttributes 0.9.2
		libblockattributes_core: LibBlockAttributes (Core) 0.9.2
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.9.2
		libblockattributes_items: LibBlockAttributes (Items) 0.9.2
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.2.1+1.17.1
		libninepatch: LibNinePatch 1.1.0
		libra: Libra 0.4.0.1
		lightestlamp: Lightest Lamps 0.9.6
		lithium: Lithium 0.7.5
		lovely_snails: Lovely Snails 1.0.3+1.17
		luckperms: LuckPerms 5.3.77
		lumiwool: Luminous Wool 1.2.0
		maelstrom_library: Maelstrom Library 1.2.2-1.17.1
		magicfungi: Magic Fungi 0.5.0-BETA+1.17.1
		magna: Magna 0.4.0-1.17.1
		matrix: Matrix 1.0.0
		maybe-data: Maybe data 1.0.1-1.17
		mc_discord_reserializer: MC Discord Reserializer 1.0.0
		mcda: MC Dungeons Armors 1.7.15
		mcdict: MCDict 2.1.0+1.17.1
		mcdw: MC Dungeons Weapons 3.6.0
		mcsa: MC Story Mode Armor 2.3.2-1.17
		mealapi: Meal API 0.3+1.17
		minecraft: Minecraft 1.17.1
		minershorizon: Miner's Horizon 1.7.2-1.17.1
		minimotd-fabric: MiniMOTD 2.0.4
		mm: Manningham Mills 2.3
		mo_glass: Mo Glass 1.5-MC1.17.1
		mob_proof_crystals: Mob proof crystals 2.2.0
		mobz: MobZ 3.2.0
		mocolors: Mo' Colors 1.2.2
		morebannerfeatures: More Banner Features 1.0.9
		morevillagers-fabric: MoreVillagersFabric 2.1.1-SNAPSHOT
		mostructures: Mo' Structures 1.3.0-pre1-1.17.1
		multipart_entities: MultipartEntities 1.1.3-1.17.1
		myron: Myron 1.6.1
		mysql_mysql-connector-java: mysql-connector-java 8.0.25
		mythic-mounts: Mythic Mounts 1.17.1-3.0
		mythicmetals: Mythic Metals 0.10.1
		naturescompass: Nature's Compass 1.17.1-2.0.1-fabric
		net_kyori_adventure-api: adventure-api 4.8.1
		net_kyori_adventure-key: adventure-key 4.8.1
		net_kyori_adventure-platform-api: adventure-platform-api 4.0.0-SNAPSHOT
		net_kyori_adventure-serializer-configurate4: adventure-serializer-configurate4 4.8.1
		net_kyori_adventure-text-feature-pagination: adventure-text-feature-pagination 4.0.0-SNAPSHOT
		net_kyori_adventure-text-minimessage: adventure-text-minimessage 4.2.0-SNAPSHOT
		net_kyori_adventure-text-serializer-gson: adventure-text-serializer-gson 4.8.1
		net_kyori_adventure-text-serializer-legacy: adventure-text-serializer-legacy 4.8.1
		net_kyori_adventure-text-serializer-plain: adventure-text-serializer-plain 4.8.1
		net_kyori_examination-api: examination-api 1.1.0
		net_kyori_examination-string: examination-string 1.1.0
		ninjaphenix_container_lib: NinjaPhenix's Container Library 1.2.4
		no_null_processors: No Null Processors - Fabric 1.0.0+1.17.1
		notenoughcrashes: Not Enough Crashes 4.1.1+1.17.1
		nyfsquivers: Nyf's Quivers Fabric-0.2.6
		observable: Observable 0.1.2-1.17
		omega-config: OmegaConfig 1.0.8
		org_fusesource_jansi_jansi: jansi 1.18
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.0
		org_jgrapht_jgrapht-core: jgrapht-core 1.1.0
		org_jline_jline: jline 3.15.0
		org_jline_jline-terminal-jansi: jline-terminal-jansi 3.15.0
		org_objenesis_objenesis: objenesis 3.2
		org_spongepowered_configurate-core: configurate-core 4.1.1
		org_spongepowered_configurate-hocon: configurate-hocon 4.1.1
		org_xerial_sqlite-jdbc: sqlite-jdbc 3.36.0
		org_yaml_snakeyaml: snakeyaml 1.29
		origins: Origins 1.1.4
		origins-classes: Origins: Classes 1.2.2
		owo: oωo 0.3.0
		packet_tweaker: Packet Tweaker 0.2.0+1.17.1
		patchouli: Patchouli 1.17.1-56-FABRIC
		pehkui: Pehkui 2.5.3+1.14.4-1.18
		persistententities: persistent entities 0.0.4
		phonos: Phonos 0.1.2+1.17
		pipe: Pipe 1.6.0
		placeholder-api: Placeholder API 1.1.2+1.17.1
		plantinajar: Plant In A Jar 2.2.2
		player-data-api: Player Data API 0.1.0+1.17.1
		playerabilitylib: Pal 1.4.0
		polymer: Polymer 0.1.8+1.17.1
		polymorph: Polymorph 0.0.14-1.17.1
		prefab: Prefab 2.1.6
		pugh_lib: Pugh Lib ${version}
		pugh_tools: Pugh Tools ${version}
		qcommon-cfg-core: qcommon-cfg-core 3.3.0
		qcommon-croco: Croco 2.1.1
		quarrymod: Industial Quarry Mod 0.5.2
		ratsmischief: Rat's Mischief 1.3.1
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		reborncore: Reborn Core 5.0.11-beta
		recipecache: recipecache 0.2.1-1.17.1
		redbits: Red Bits 1.10.1
		repurposed_structures: Repurposed Structures 2.5.7+1.17.1
		reroll: Reroll 1.3.0-1.17.1
		resourceful_tools: Resourceful Tools 1.1.22
		respawnablepets: Respawnable Pets 1.17-5
		rhino: Rhino 1701.1.5-build.71
		roughlyenoughitems: Roughly Enough Items 6.1.330
		rpgstats: RPGStats 4.2.2+1.17.1
		rswires: RSWires 4.11.2
		sandwichable: Sandwichable 1.2-rc2+1.17
		schmucks: Schmucks 1.4.0
		secretrooms: Secret Rooms 1.1.0+1.17
		seedy-behavior: Seedy Behavior 1.0.2+1.17.1
		server_translations_api: Server Translations API 1.4.8+1.17
		servertick: Server Tick 1.5
		sgui: sgui 1.0.0-rc5+1.17.1
		shulkerboxtooltip: Shulker Box Tooltip 3.0.3+1.17.1
		shulkerutils: shulkerutils 1.0.4-1.17
		silkspawners: SilkSpawners 1.0.2
		skyvillages: Sky Villages 1.0.1-fabric
		someforgepatchesported: Some Forge Patches Ported 1.0.1
		somnus: Somnus API 0.0.14-1.17.1
		soulbound: Soulbound 2.0.0
		spark: spark 1.6.1
		spawnprotectiontweaks: SpawnProtectionTweaks 0.3+1.17.1
		stacc: Stacc 1.2.3
		staffofbuilding: Staff of Building 1.3.2-1.17
		starlight: Starlight 1.0.0+fabric.73f6d37
		static-content: Static Content 1.0.2-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stonecutter_recipe_tags: Stonecutter Recipe Tags 1.1.0
		stoneholm: Stoneholm 1.3
		storagecabinet: Storage Cabinet 1.4.1
		strawdummy: Straw Dummy 1.5.0
		structure-helpers: Structure Helpers 3.2.0
		structurized: Structurized 1.3.0
		styledchat: Styled Chat 1.2.0
		styledplayerlist: Styled Player List 2.1.2
		tabtps-fabric: TabTPS 1.3.10
		team_reborn_energy: Energy 2.0.0-beta1
		techreborn: Tech Reborn 5.0.11-beta
		tellme: TellMe 0.9.0
		terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
		terralith: Terralith for Fabric 1.6.1
		things: Things 0.2.6
		toms_storage: Tom's Simple Storage Mod 1.1.18
		transportables: Transportables 1.0.6
		trashslot: TrashSlot 10.0.0+0
		trinkets: Trinkets 3.0.4
		truerooms: True Secret Rooms 1.1.5
		unforgivingvoid: Unforgiving Void 3.1.0+1.17.1
		universal-graves: Universal Graves 1.1.4+1.17.1
		untitledduckmod: Untitled Duck Mod 0.3.0
		upgradedshulkers: Upgraded Shulkers 1.1.1-1.17
		urns: Urns 1.0.1
		valley: ValleyCraft 1.3.2
		vanish: vanish 1.2.6
		veinmining: Vein Mining 0.0.11-1.17.1
		villager-hats: Villager Hats Mod 1.2.1
		villagernames: Villager Names 2.0.1
		voidtotem: Void Totem (Fabric) 1.17.0-1.0.0
		voidz: VoidZ 1.0.5
		ward_blocks: Ward Blocks 1.1.9
		waystones: Waystones 2.2.1
		winged: Winged Mod 1.17.1-3.0.0
		wirelessnetworks: Wireless Networks 1.3.1
		wrenchable: Wrenchable 1.1.0+1.17
		wthit: wthit 3.11.2
		xaerominimap: Xaero's Minimap 21.21.0
		xaeroworldmap: Xaero's World Map 1.18.2
		xlpackets: XLPackets 2.0-1.17
		xps: Xp Obelisk 0.2.2.r_for_1.17.x_Fabric
		yungsapi: YUNG's API 1.17-Fabric-19
		zihlaunchpads: ZIHLaunchpads 1.2.0
	Player Count: 10 / 10; [class_3222['epixphany'/458, l='ServerLevel[world]', x=7169.95, y=66.74, z=-8231.05], class_3222['Dres_Tiefling'/753, l='ServerLevel[world]', x=1257.82, y=118.00, z=-111.93], class_3222['RojinUK'/1037, l='ServerLevel[world]', x=-1593.47, y=-32.00, z=14075.40], class_3222['JeezyOG'/26537, l='ServerLevel[world]', x=7082.30, y=92.32, z=-8255.30], class_3222['TheOxOwl'/49035, l='ServerLevel[world]', x=-5152.20, y=56.00, z=-447.64], class_3222['that_different'/604, l='ServerLevel[world]', x=1143.19, y=129.00, z=-73.33], class_3222['chineseweird'/69435, l='ServerLevel[world]', x=1943.30, y=46.00, z=375.30], class_3222['Deveractive1'/72337, l='ServerLevel[world]', x=987.53, y=62.00, z=-1829.38], class_3222['NativeN3rd'/79491, l='ServerLevel[world]', x=3063.04, y=63.56, z=-2174.89], class_3222['hanasaseru'/11211, l='ServerLevel[world]', x=1.42, y=92.00, z=113.38]]
	Data Packs: vanilla, Fabric Mods, dimdoors/classic, dimdoors/default, secretrooms:server_pack, file/1-noblazeborn, file/2-nophantom, file/Repurposed_Structures-Better_Strongholds_Fabric_Beta.zip, file/Repurposed_Structures-Charm.zip, file/Repurposed_Structures-Farmers_Delight_Fabric.zip, file/Repurposed_Structures-More_Villagers_Fabric.zip, file/Salt.zip, file/doom, file/gobber2_datapack
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), Patchouli (patchouli)

**Comment by Hubry** [comment]
56 is not latest, update to 58
