### ISSUE TITLE
[1.17.1] Custom book model not working (Forge)

### ISSUE THREAD

**Issue by JaisDK** [VazkiiMods/Patchouli#465]
Just updated my guide book to 1.17.1 and the custom model is not working

Forge 1.17.1-37.0.109
Patchouli 1.17.1-58-SNAPSHOT

Book JSON

https://github.com/JDKDigital/productive-bees/blob/dev-1.17.1/src/main/resources/data/productivebees/patchouli_books/guide/book.json

[latest.log](https://github.com/VazkiiMods/Patchouli/files/7590752/latest.log)
[debug.log](https://github.com/VazkiiMods/Patchouli/files/7590753/debug.log)

**Comment by JaisDK** [comment]
![image](https://user-images.githubusercontent.com/15868585/143215150-a8be4dfb-f27d-460c-b8eb-87462d5223b5.png)

**Comment by williewillus** [comment]
this race condition should hopefully be patched
