### ISSUE TITLE
Annoying log spam due to missing lang files

### ISSUE THREAD

**Issue by ChiefArug** [VazkiiMods/Patchouli#466]
My log is spammed with this message, once for each page in every patchouli manual I have. (almost 400 lines for only two mods with manuals)
` [Render thread/WARN]: Failed to load pneumaticcraft:patchouli_books/book/en_nz/categories/programming.json. Switching to fallback.`

It gets really annoying as I am very aware that barely any mods will have a translation for the language I have set (New Zealand English) and it would be almost identical to the default American English anyway.

I request a config option to disable this, as it is pretty pointless and uneeded. Or condense it into a single, more accurate line: 
`Page(s) in Manual Name have been found missing translations for the currently set language (en_nz), switching those to the default.`

**Comment by williewillus** [comment]
what version? This log message was silenced in recent versions, iirc.

**Comment by ChiefArug** [comment]
Patchouli `1.16.4-53.2`
Minecraft `1.16.5`
Forge `36.2.8`

**Comment by Hubry** [comment]
The logs were silenced sometime during 1.17. The question is: do we backport that change?

**Comment by ChiefArug** [comment]
Closed because its been a year and I suspect 1.16.5 is not going to get an update
