### ISSUE TITLE
Game crash when using Crock Pot mod's Patchouli book to shift-and-right-clicking on a its crop block

### ISSUE THREAD

**Issue by RisingInIris2017** [VazkiiMods/Patchouli#470]
### Mod loader

Forge

### Minecraft version

1.16.5

### Patchouli version

1.16.4-53.2

### Modloader version

Forge 36.2.18

### The latest.log file

https://paste.ubuntu.com/p/6KTd2Cb5fW/

### Issue description

Simply hold the manual of Crock Pot, press down Shift button and right-click on a Crock Pot mod's crop block,
then game instantly crashes.

### Other information

I have post the same issue to Crock Pot mod's repo:
https://github.com/SihenZhang/CrockPot/issues/47
Maybe it helps.

**Comment by SeraphJACK** [comment]
Duplicated #374 .

**Comment by williewillus** [comment]
^
