### ISSUE TITLE
guide

### ISSUE THREAD

**Issue by xz123456xz** [VazkiiMods/Patchouli#472]
### Mod loader

Forge

### Minecraft version

1.17.1

### Patchouli version

1.17.1-57

### Modloader version

forge-1.17.1-37.0.108

### The latest.log file

No item

### Issue description

The Twilight Forest The appearance of the guide item is not displayed correctly.

![image](https://user-images.githubusercontent.com/52368359/144695629-c6dd828e-0172-491b-8f02-cc1a7f8cf501.png)

**Comment by williewillus** [comment]
same as #465
