### ISSUE TITLE
Crash 1.18

### ISSUE THREAD

**Issue by itsdinkd** [VazkiiMods/Patchouli#474]
### Mod loader

Fabric

### Minecraft version

1.18

### Patchouli version

Latest

### Modloader version

12.8

### Modpack info

Another Quality Modpack 2 (1.18 Unreleased)

### The latest.log file

https://crashy.net/s1p2stTXJ9kiwml9nkwS

### Issue description

Opened a patchouli book in third person and crashed

**Comment by williewillus** [comment]
hmm, not sure if this is Patchouli related as we don't touch player rendering (where the crash happened). Could it be that specific item has special rendering?
