### ISSUE TITLE
Use of Fabric API's internal API

### ISSUE THREAD

**Issue by LambdAurora** [VazkiiMods/Patchouli#476]
### Mod loader

Fabric

### Minecraft version

1.18

### Patchouli version

1.18-60-FABRIC

### Modloader version

Fabric Loader 0.12.11 + Fabric API QSL 0.44.0 (WIP)

### Modpack info

https://www.curseforge.com/minecraft/modpacks/all-of-fabric-5

### The latest.log file

https://paste.ee/p/ZkDQo

### Issue description

Patchouli is using unstable internals of Fabric API here:
https://github.com/VazkiiMods/Patchouli/blob/b4e7214c0f0e5ae64938b00bb43c7b0537bc3bbc/src/main/java/vazkii/patchouli/common/multiblock/StringStateMatcher.java#L43

This causes a lot of issues for Fabric API QSL, which is a reimplementation of Fabric API using QSL instead, but outside of this context it can also lead to unexpected breakage if normal Fabric API changes its internals. 

`TagFactory.BLOCK#create` should be used instead, the tag reference will still be auto-updating.

**Comment by Hubry** [comment]
I think that got fixed during the reorganization into the multiloader setup.
