### ISSUE TITLE
Endless Reload Loop

### ISSUE THREAD

**Issue by KenjieDec** [VazkiiMods/Patchouli#479]
### Mod loader

Fabric

### Minecraft version

1.18.1

### Patchouli version

1.18.1

### Modloader version

Fabric: 0.12.11 + API: 0.44.0

### Modpack info

https://pastebin.com/raw/ApdAeftY

### Stacktrace

https://pastebin.com/raw/irtmcgvd, https://pastebin.com/raw/7xRxUxXj

### Issue description

Reloading Texture packs loop

### Steps to reproduce

1. Open Minecraft
2. Play

### Other information

Endless loop.

**Comment by Hubry** [comment]
That's not a `latest.log` file, just a fragment of a stacktrace (not even a full one, I still see `Caused by:`). Please, do not assume less information can be provided. If anything, we prefer information overload than scraps.

**Comment by KenjieDec** [comment]
> That's not a `latest.log` file, just a fragment of a stacktrace (not even a full one, I still see `Caused by:`). Please, do not assume less information can be provided. If anything, we prefer information overload than scraps.

Yeah, sorry about that, I've updated the pastebin link for longer stacktrace
