### ISSUE TITLE
Allow Ordering of entries in a category, and ordering of categories in the book's landing page

### ISSUE THREAD

**Issue by lol123123987** [VazkiiMods/Patchouli#480]
### Describe the feature

add a variable in an entry/category's json file that reads an integer, and it orders them in their menus accordingly, instead of alphabetically. As of now, i don't see a clean way of ordering your entries/categories when you have more than 9 of them (ordering them numerically). Thes feature would completely solve that problem.

**Comment by DaFuqs** [comment]
This is already a thing. Both Categories and Entries have a property "sortnum":

https://vazkiimods.github.io/Patchouli/docs/reference/category-json
https://vazkiimods.github.io/Patchouli/docs/reference/entry-json
