### ISSUE TITLE
1.18.1 Forge Not Displaying Entry Pages

### ISSUE THREAD

**Issue by ClaudiusMinimus** [VazkiiMods/Patchouli#483]
### Mod loader

Forge

### Minecraft version

1.18.1

### Patchouli version

1.18.1-61

### Modloader version

39.0.5 - 39.0.7

### Modpack info

https://www.curseforge.com/minecraft/modpacks/create-on-a-potato/files/3534557

### The latest.log file

https://pastebin.com/beYcB6Wb

### Issue description

A book I had made that works fine in 1.16.5 does not show any entry pages as shown in the below screenshots. 

I also attached the zipped patchouli_books folder. 

### Other information

![image](https://user-images.githubusercontent.com/17887664/146857978-a6a89639-66b2-4037-9120-537d82034b70.png)
![image](https://user-images.githubusercontent.com/17887664/146858028-780d8df2-d982-4eed-b68e-b4368f281ea4.png)
[patchouli_books.zip](https://github.com/VazkiiMods/Patchouli/files/7749233/patchouli_books.zip)

**Comment by williewillus** [comment]
You'll need to do some adjustments when crossing above 1.17. See https://vazkiimods.github.io/Patchouli/docs/upgrading/upgrade-guide-117

**Comment by ClaudiusMinimus** [comment]
I thought I did, but will double-check. Thanks!

**Comment by ClaudiusMinimus** [comment]
Thanks, I was using the wrong namespace, when I switched to "patchouli" it worked.
