### ISSUE TITLE
Modrinth Support

### ISSUE THREAD

**Issue by Ecorous** [VazkiiMods/Patchouli#487]
### Describe the feature

Add Modrinth Support

**Comment by williewillus** [comment]
Sure.

https://modrinth.com/mod/patchouli

**Comment by Ecorous** [comment]
Thanks!

**Comment by goldenapple3** [comment]
@williewillus would you consider also uploading 1.16 versions to Modrinth?

**Comment by goldenapple3** [comment]
Just now noticed more uploads, thanks a lot!
