### ISSUE TITLE
[Fabric 1.18.1] Unable to connect to a LAN world after entering a nether portal

### ISSUE THREAD

**Issue by Vapaman** [VazkiiMods/Patchouli#488]
### Mod loader

Fabric

### Minecraft version

1.18.1

### Patchouli version

1.18.1-61-fabric

### Modloader version

Fabric Loader 0.12.12; API 0.45.0+1.18

### Modpack info

Custom pack, see mods in log. Also a custom datapack for knife recipes

### The latest.log file

https://gist.github.com/Vapaman/966d236705c790ba60cb1ffca6d05a06

### Issue description

Unable to to load into the world properly, gets stuck on loading world indefinitely.
From the crashed players side:
https://gist.github.com/Vapaman/966d236705c790ba60cb1ffca6d05a06
https://gist.github.com/Vapaman/ebc625c9c6396add3e2c2dca1dee7925
From the hosts side:
https://gist.github.com/Vapaman/3953c398162436abe3f3ab387576b095

There is no crash report as the game had to be closed manually.

### Steps to reproduce

**NOTE!** Cannot reproduce in creative, seems to be some strange occurence
------------------------------------
What happened before crash:
1. Enter nether portal
2. Rigth click with wand of forest on the nether portal
3. Get stuck loading
(Note: the client that crashed had a patchouli book (Lexica Botania) in their inventory)
### Other information

Could be caused by Botania, I'm not sure.

**Comment by Hubry** [comment]
I think that's a vanilla/general modded bug, possibly related to https://bugs.mojang.com/browse/MC-215960. It occurs only on updating older worlds and happens with a variety of mods, so I don't think it's our fault.
