### ISSUE TITLE
All Patchouli books show up as one item in JEI

### ISSUE THREAD

**Issue by freopt** [VazkiiMods/Patchouli#489]
### Mod loader

Forge

### Minecraft version

1.18.1

### Patchouli version

1.18.1-61

### Modloader version

Forge 39.0.8

### The latest.log file

https://gist.github.com/freopt/f8350583729d4be1ca6b8da3d525b30c

### Issue description

Title. If you @patchouli in Jei only one book shows (mystical agriculture seems to have priority over the other mods I used), and if you look up the recipe it shows all of the patchouli books. Looking up the name of the other books does not work as they aren't registered in JEI.

### Steps to reproduce

Download multiple mods that use Patchouli and JEI
Try to look up multiple different books
See that only one exists

### Other information

I assume it's because the books are the same item with different nbt but this didnt happen in previous versions of MC

**Comment by williewillus** [comment]
fixed in the next version
