### ISSUE TITLE
Crash when reloading textures

### ISSUE THREAD

**Issue by freopt** [VazkiiMods/Patchouli#491]
### Mod loader

Forge

### Minecraft version

1.18.1

### Patchouli version

1.18.1-61

### Modloader version

39.0.8

### The latest.log file

https://bytebin.lucko.me/nMlNFuGQCU

### Issue description

Using F3+T to reload textures crashes the game

**Comment by williewillus** [comment]
Please try on version 63

**Comment by freopt** [comment]
seems to be fixed
