### ISSUE TITLE
Crash when using Fabric Loader 0.12.12 with Patchouli-1.18.1-62-FABRIC.jar

### ISSUE THREAD

**Issue by jezzballin** [VazkiiMods/Patchouli#492]
### Mod loader

Fabric

### Minecraft version

1.18.1

### Patchouli version

1.18.1-62-FABRIC

### Modloader version

Fabric Loader 0.12.12 Fabric API 0.45

### Modpack info

https://www.curseforge.com/minecraft/modpacks/fabric-fun-pack

### The latest.log file

https://pastebin.com/yZM1hDLb

### Issue description

When launching a server/client with the latest Patchouli update alongside the most recent Fabric API and Loader, this crash occurs.

### Steps to reproduce

1.Install Fabric API 0.45 and Fabric Loader 0.12.12
2.Install Patchouli 1.18.1-62-FABRIC.jar
3.Attempt to launch MC

**Comment by williewillus** [comment]
should've used service loaders for this :(
Will look into it shortly. In the meantime, going back to 61 should fix it.

**Comment by williewillus** [comment]
a03c930e1db6f3ff49cf6f6e5227cf20936d4307
