### ISSUE TITLE
ru_ru.json error

### ISSUE THREAD

**Issue by MJRamon** [VazkiiMods/Patchouli#493]
### Mod loader

Fabric

### Minecraft version

1.18.1

### Patchouli version

Patchouli-1.18.1-61-FABRIC

### Modloader version

0.12.12 / fabric-api-0.45.0+1.18

### The latest.log file

none needed

### Issue description

Patchouli Russian language json validation error.
```
Skipped language file: patchouli:lang/ru_ru.json (com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 94 column 3 path $.patchouli.gui.lexicon.button.history)
```

Missed comma at
```
"patchouli.gui.lexicon.button.history": "История"
```

**Comment by Hubry** [comment]
Seems like the last contributor didn't even test their Russian translation ingame.
