### ISSUE TITLE
Don't generate book leads to "Air" title

### ISSUE THREAD

**Issue by Globox1997** [VazkiiMods/Patchouli#496]
### Mod loader

Fabric

### Minecraft version

1.18.1

### Patchouli version

1.18.1-63

### Modloader version

Fabric: Loader 0.12.12 + API 0.45.0

### The latest.log file

https://pastebin.com/gnJLqiT3

### Issue description

inside the book.json:
`"dont_generate_book": true`

This will lead to "Air" title:
![image](https://user-images.githubusercontent.com/55102939/148130819-bdf2f696-8740-4358-8220-6943b78d8108.png)

### Steps to reproduce

1. put `"dont_generate_book": true` inside the book.json file
2. load in world and check out the patchouli book

**Comment by Hubry** [comment]
Post your `book.json`. Last time I saw this issue it was caused by someone misspelling the `custom_book_item` key.

**Comment by Globox1997** [comment]
Uh I miss understood this line:
![image](https://user-images.githubusercontent.com/55102939/148199514-5ce8f19f-6b16-4776-87dd-d2e072ef5a81.png)
But now it makes sense, just forgot to use the `custom_book_item ` , thanks for the help
