### ISSUE TITLE
BetterEnd guidebook doesn't open in hand

### ISSUE THREAD

**Issue by MJRamon** [VazkiiMods/Patchouli#498]
### Mod loader

Fabric

### Minecraft version

1.18.1

### Patchouli version

Patchouli-1.18.1-64-FABRIC

### Modloader version

0.12.12 /  fabric-api-0.45.0+1.18

### The latest.log file

No log errors

### Issue description

https://github.com/paulevsGitch/BetterEnd/issues/399

**Comment by Hubry** [comment]
Closing as the issue is on their side.
