### ISSUE TITLE
Rendering Crash - Modern Industrialization book -> site with diamond drill (the steam age pages)

### ISSUE THREAD

**Issue by xR4YM0ND** [VazkiiMods/Patchouli#499]
### Mod loader

Fabric

### Minecraft version

1.18.1

### Patchouli version

1.18.1-64

### Modloader version

Fabric: Loader 0.12.12

### Modpack info

https://www.curseforge.com/minecraft/modpacks/the-progressor

### The latest.log file

https://gist.github.com/SpigotDE/f8abf1ee0aaa177dfb8f30b48af4e430

### Issue description

Rendering Crash with Modern Industrialization

seems like : 

Modern Industrialization:
 - Diesel Tool 
 - Steam Drill
 - maybe more?

### Steps to reproduce

Open MI book

get to the Steam Page

scroll

at the page with the diamond drill it crashed

### Other information

[crash-2022-01-13_21.49.26-client.txt](https://github.com/VazkiiMods/Patchouli/files/7866018/crash-2022-01-13_21.49.26-client.txt)

**Comment by xR4YM0ND** [comment]
updated kiwi mod to 5.2.3 -> still crashes

**Comment by JakeSublime** [comment]
I can confirm i am also having this same issue.

**Comment by williewillus** [comment]
Post a new log

**Comment by JakeSublime** [comment]
[crash-2022-01-23_16.00.37-client.txt](https://github.com/VazkiiMods/Patchouli/files/7929999/crash-2022-01-23_16.00.37-client.txt)

Does this work for you? i just drag and dropped the text file.

**Comment by xR4YM0ND** [comment]
Should be fixed with LevelZ version 1.1.6 https://www.curseforge.com/minecraft/mc-mods/levelz/files/3652950

if it still exists pls open a new issue
