### ISSUE TITLE
Underline format code does not work

### ISSUE THREAD

**Issue by Hekera** [VazkiiMods/Patchouli#500]
### Mod loader

Forge

### Minecraft version

1.16.5

### Patchouli version

53.1 onward

### Modloader version

Forge 36.2.22

### The latest.log file

https://pastebin.com/wpwkWjHN

### Issue description

The underline format code $(n) does not get parsed as an underline, despite working in previous versions. 

https://cdn.discordapp.com/attachments/434101214548852746/929791544930762782/unknown.png 

### Steps to reproduce

1. Write a guidebook for the Thermal Series with Patchouli version 52 or below
2. Use $(n) to successfully underline text
3. Update Patchouli to version 53.1+
4. Notice that your text is no longer underlined
5. Cry

**Comment by williewillus** [comment]
hmm, do the other format codes work?

**Comment by Hekera** [comment]
I haven't tested them extensively, but I think bold and italics work.

**Comment by williewillus** [comment]
@Alwinfy related to your latest changes on 1.16?

**Comment by williewillus** [comment]
update: this was apparently never implemented for years even though the docs had it, lol

has been implemented and will be released in 65 shortly
