### ISSUE TITLE
Book created on mod having default ID

### ISSUE THREAD

**Issue by LuanHimmlisch** [VazkiiMods/Patchouli#501]
### Mod loader

Forge

### Minecraft version

1.18.1

### Patchouli version

1.18.1-63

### Modloader version

Forge 39.0.19

### The latest.log file

https://gist.github.com/LuanHimmlisch/89eb0d3746a81b041642e69826cf65f3

### Issue description

The ID of the book is the default Patchouli one although the book is being created from a Mod.

![imagen](https://user-images.githubusercontent.com/46875694/149648797-2d72a752-0a13-432e-b36b-3b920ef4bb8f.png)

The rather confusing documentation doesn't help either, it's instructed that the folder where the books are specified needs to be named `patchouli_books` just to then say in some paragraphs after that if the books are being loaded from this folder the book id will be the default one? 

![imagen](https://user-images.githubusercontent.com/46875694/149649076-57b091a6-9494-4797-ac72-8702b47a4da8.png)

Then what folder is not an "external" one?

### Steps to reproduce

1. Install Patchouli
2. Create a book
3. Done

**Comment by Hubry** [comment]
The ID of the *book* you are showing is `latinos:latinos_guidebook`. Book != book *item*. The default book item is provided by Patchouli, what book it refers to depends on NBT data on the item stack. You can provide your own book item by setting `dont_generate_book` in `book.json` to true and pointing `custom_book_item` at your own item you register, and calling the Patchouli API method to open the book in the use method.

The "external `patchouli_books` folder" docs are talking about is the one in the root of the game instance folder, used for modpack books.

Also, please ask this kind of stuff on Discord first.
