### ISSUE TITLE
Game crashes whenever I open a book

### ISSUE THREAD

**Issue by SheriffOchs** [VazkiiMods/Patchouli#502]
### Mod loader

Forge

### Minecraft version

1.16.5

### Patchouli version

Patchouli-1.16.4-53.2.jar

### Modloader version

36.2.20

### Modpack info

https://www.curseforge.com/minecraft/modpacks/create-above-and-beyond

### The latest.log file

https://pastebin.com/5jZAswgj

### Issue description

When I open any Patchouli-related book (Occultism's guidebook, the Buddycard mod's guidebook, etc.) my game immediately crashes. I get the same crash log every time accompanied by error code -1. I've reinstalled Patchouli as well as the entire modpack, I've updated my java, I've restarted my PC, and I've even tried on different SP and MP worlds, both in creative and survival. None of the other players of this modpack that I've spoken to (including those on my MP server) have had this issue, and it would likely be useful to note that I did not have this issue a few days ago.  

### Steps to reproduce

1. Pick up / craft / add any Patchouli book to your inventory
2. Open book
3. Crash

**Comment by e11k4t** [comment]
I can confirm same behavior just with small difference, my ModLoader is 36.2.9

**Comment by khjxiaogu** [comment]
I found a similiar problem when using ctrl to check an item's entry.
