### ISSUE TITLE
Make default `textOverflowMode` mode alterable per book

### ISSUE THREAD

**Issue by Aizistral** [VazkiiMods/Patchouli#506]
### Describe the feature

Make it so that default way of handling text overflow can be changed for any given book, supposedly through book's main `.json`.

### Additional context

In my mod I make text fit perfectly on pages (and demand the same from localizators), but default `RESIZE` mode would nonetheless kick in and screw up some pixels when rendering the font here and there, even though the text would have looked absolutely fine without any resizing. This is sufficiently annoying to motivate me to implement some temporary hacks to make things as god intended, but perhaps this can be addressed on the level of Patchouli itself.

**Comment by williewillus** [comment]
sure
