### ISSUE TITLE
Leaving off `name` in a BookEntry will NPE in random places, should probably be validated somewhere

### ISSUE THREAD

**Issue by quat1024** [VazkiiMods/Patchouli#509]
### Mod loader

Fabric

### Minecraft version

1.18.1

### Patchouli version

1.18.1-64-FABRIC

### Modloader version

Fabric Loader 0.12.11 / fabric 0.44.0+1.18

### Modpack info

Incorporeal dev instance

### The latest.log file

https://paste.ee/p/lSEfv

### Issue description

If you leave off `name` in an entry's json, the game will unceremoniously NPE in random places when operating on it.

In the linked paste.ee, I crashed the game by opening the Entry Index while there were two entries with the same `sortnum` with one missing a `name`:

https://github.com/VazkiiMods/Patchouli/blob/325021b725f58c8930429ef0299955538aa7a03e/Common/src/main/java/vazkii/patchouli/client/book/BookEntry.java#L192

If it doesn't happen there, it'll probably NPE here when trying to draw a button to the screen: 

https://github.com/VazkiiMods/Patchouli/blob/325021b725f58c8930429ef0299955538aa7a03e/Common/src/main/java/vazkii/patchouli/client/book/gui/button/GuiButtonEntry.java#L62-L68

### Steps to reproduce

1. Write an entry json that doesn't include "name"
2. Game explodes much later than it should

### Other information

I would prefer if this failed-fast, possibly by failing to load the entry, or warning in the console while replacing the name with "unnamed" or something.

Workspace where i ran in to this: https://github.com/quat1024/incorporeal-3/commit/428dcc2ffebe0a4045df35f9733a8e7995dc207c

**Comment by quat1024** [comment]
Related: #291

**Comment by williewillus** [comment]
Lots more validation is being done now on load
