### ISSUE TITLE
Changing recipes break the guide book

### ISSUE THREAD

**Issue by pafeuu** [VazkiiMods/Patchouli#511]
### Mod loader

Forge

### Minecraft version

1.16.5

### Patchouli version

1.16.4-53.2

### Modloader version

Forge 36.2.29

### The latest.log file

https://gist.github.com/pafeuu/e06184d251aaa6f9c695324eac2ea7df

### Issue description

Changing recipes that are shown in natures aura guide book cause it to not render most of the content. I already reported this to nature's aura author and he said to forward the issue here.

https://github.com/Ellpeck/NaturesAura/issues/238

**Comment by williewillus** [comment]
Please try to fix the other broken recipes/loot tables in your pack first. The log is almost impossible to read because of everything going on.

**Comment by pafeuu** [comment]
[latest.log](https://github.com/VazkiiMods/Patchouli/files/8190056/latest.log)
My bad. Here is log from clean istance with just kubejs, patchouli and natures aura with just one recipe changed

**Comment by williewillus** [comment]
Looks like you have a bad item?

> Caused by: java.lang.RuntimeException: Unknown item ID: naturesaura:altar
	at vazkii.patchouli.common.util.ItemStackUtil.loadStackFromString(ItemStackUtil.java:82) ~[patchouli:1.16.4-53.2]

**Comment by williewillus** [comment]
^ please seek help on Discord or IRC if you still need it
