### ISSUE TITLE
Is crashing in my 1.18.2 modpack

### ISSUE THREAD

**Issue by TheButterbrotMan** [VazkiiMods/Patchouli#514]
### Mod loader

Fabric

### Minecraft version

1.18.2

### Patchouli version

1.18.2-66

### Modloader version

0.13.3

### Modpack info

https://www.curseforge.com/minecraft/modpacks/deathdusk

### The latest.log file

https://bytebin.lucko.me/Qqy274zDDx

### Issue description

Is crashing at starting.

**Comment by williewillus** [comment]
can you include the full log?

**Comment by TheButterbrotMan** [comment]
It is

**Comment by Hubry** [comment]
This is just the stacktrace. Open the `logs` folder in the instance and attach `latest.log`, you provided almost no info.

**Comment by TheButterbrotMan** [comment]
There is no latest.log, it crashes right after starting.
