### ISSUE TITLE
Creating a book

### ISSUE THREAD

**Issue by Magic1617** [VazkiiMods/Patchouli#515]
### Mod loader

Fabric

### Minecraft version

1.18.1

### Patchouli version

1.18.1-65-FABRIC

### Modloader version

Fabric: Loader 0.13.3 + Api 0.46.6

### The latest.log file

https://gist.github.com/Magic1617/98a148effd3ab09f4b35998d8f70fda2

### Issue description

When I try to create a book following the wiki, the book will not load and the patchouli book has "invalid book no id defiend"
I wanted to create a book for custom modpack so some help with this would be appreciated.

### Other information

There are other mods present but I'm not sure if it's relevant to this issue

**Comment by Magic1617** [comment]
After some more reading I found a solution. Basically I had to use different program for writing json files.

**Comment by Papierkobold2025** [comment]
Hello,
I've been dealing with this exact problem for a while and I just cannot figure out how to solve it.
What program did you use that solved your problem?
Thank you
