### ISSUE TITLE
Add ability to pause game via toggle button

### ISSUE THREAD

**Issue by CalaMariGold** [VazkiiMods/Patchouli#516]
### Describe the feature

The ability to toggle whether or not to pause the game in a SP world while reading the book would greatly improve the experience for many modpacks. Sometimes you want time to pass, and sometimes you need extra time to read.

Having this feature would be perfect in modpacks like Rebirth of the Night where the first few hours are crucial to surviving.

Thank you <3

**Comment by williewillus** [comment]
won't happen for 1.12, but sure, open to adding this on latest versions.

**Comment by CalaMariGold** [comment]
Would you be open to accepting a pull request that adds the functionality to 1.12.2 as well?

**Comment by CalaMariGold** [comment]
Feature added in 1.12.2 fork: https://legacy.curseforge.com/minecraft/mc-mods/patchouli-rofl-edition

Also in newer patchouli versions so I'll close this.
