### ISSUE TITLE
Minecraft has crashed!

### ISSUE THREAD

**Issue by TheButterbrotMan** [VazkiiMods/Patchouli#517]
### Mod loader

Fabric

### Minecraft version

1.18.2

### Patchouli version

1.18.2-66-FABRIC

### Modloader version

Fabric: Loader 0.13.3 + API 0.48.0+1.18.2

### The latest.log file

https://bytebin.lucko.me/O9lleHQiLV

### Issue description

Is crashing right after starting client.

**Comment by TheButterbrotMan** [comment]
Its an issue connected to https://www.curseforge.com/minecraft/mc-mods/public-gui-announcement

**Comment by TheButterbrotMan** [comment]
https://github.com/ArtixAllMighty/PublicGuiAnnouncement/issues/11

**Comment by williewillus** [comment]
what makes you think this is related to patchouli?

**Comment by williewillus** [comment]
Patchouli is in the stack, but the mixin transform is failing for another unrelated class. Not sure if we're the cause here. Try reducing the set of mods into you get a repro with just patchouli and something else.
