### ISSUE TITLE
Bug #518

### ISSUE THREAD

**Issue by Ideki** [VazkiiMods/Patchouli#519]
### Mod loader

Forge

### Minecraft version

1.18.2

### Patchouli version

1.18.2-66-SNAPSHOT

### Modloader version

forge:1.18.2-40.0.15

### The latest.log file

https://pastebin.com/T0RAwUsd

### Issue description

Please re-open bug #518 as my compilation still crash

**Comment by Hubry** [comment]
Did you regen your IDE runs? Anyways, if you need support, come to discord, this isnt the place for it
