### ISSUE TITLE
Block transparency is not respected on the multiblock page

### ISSUE THREAD

**Issue by IchHabeHunger54** [VazkiiMods/Patchouli#520]
### Mod loader

Forge

### Minecraft version

1.18.1

### Patchouli version

1.18.1-65

### Modloader version

39.0.66

### Modpack info

-

### The latest.log file

Not a crash, so none.

### Issue description

This somewhat mirrors #201 , which, as it seems, has been fixed.

The multiblock page does not respect block transparency, as seen in the images below.
![2022-03-17_11 43 23](https://user-images.githubusercontent.com/52419336/158801153-30e7a307-5f10-4125-bb13-59561edb8f26.png)
![2022-03-17_11 43 17](https://user-images.githubusercontent.com/52419336/158801169-196c1c72-921f-42da-8986-c50f1430bd71.png)

### Steps to reproduce

1. Create a block and set the cutout or translucent render type on it.
2. Use that block in a multiblock.
3. Display that multiblock in a multiblock page.

### Other information

I can confirm this is happening with RenderType.cutout() and RenderType.translucent().
It is possible that this happens with other types as well, but I haven't tested it.

**Comment by williewillus** [comment]
hm, I can't get this to happen with vanilla's cutout blocks (tall grass and glass). Does it happen for those blocks for you?

**Comment by williewillus** [comment]
ah, actually. This is the same issue as #201. The fix was accidentally dropped when we merged forge/fabric codebases together.
