### ISSUE TITLE
Crash while loading Minecraft. java.util.zip.ZipError: zip END header not found

### ISSUE THREAD

**Issue by Kasia1403** [VazkiiMods/Patchouli#523]
### Mod loader

Forge

### Minecraft version

1.12.2

### Patchouli version

1.0-23.6

### Modloader version

Forge 14.23.5.2860

### The latest.log file

https://paste.ee/p/9fipo

### Issue description

Crash while loading Minecraft. java.util.zip.ZipError: zip END header not found

**Comment by williewillus** [comment]
There is way too much going on in your environment. Reduce it down to the minimum set of mods that causes the crash, please. And make sure the crash is reproducible every time. If it's transient, then I would suspect OS or hardware issues.

**Comment by Kasia1403** [comment]
What if I don't know which mods to disable ?

**Comment by Kasia1403** [comment]
debug.log

https://paste.ee/p/EZvaN

Hope this will help.

**Comment by Kasia1403** [comment]
Hello VazkiiMods, could someone help me ?

**Comment by williewillus** [comment]
Disable half, try and see if it happens. Repeat, each time removing more mods until the problem goes away. Then you know the problem mod was in the half that you removed.

**Comment by Kasia1403** [comment]
Why in the crash log it says suspected mods Patchouli ?

**Comment by Kasia1403** [comment]
@williewillus Whyyy could'n You help me and do a test without me ? :( My computer is weak ( very slow and only 16 GB RAM, while I have seen that Youtubers have 32 GB RAM ). :( I'm disabled and can't have better computer. My mom disagrees.

**Comment by williewillus** [comment]
Patchouli has millions of players. I have a full time job and my own life and cannot afford the time to help every single one with their tech issues. I already gave you a plan to try to debug the issue, please try it.

This should be closed anyways as 1.12 is no longer supported. Redownload your pack and check for file corruption.

**Comment by Kasia1403** [comment]
@williewillus  Do You know maybe if Patchouli is compatible or incompatible with Village And Pillage And Pillage And Village mod ( VPPV v4 ) ?

**Comment by Kasia1403** [comment]
How to redownload private modpacks ?
