### ISSUE TITLE
Error code 1 crash when opening minecraft with vivecraft 1.16.5

### ISSUE THREAD

**Issue by ArachKnightt** [VazkiiMods/Patchouli#533]
### Mod loader

Forge

### Minecraft version

1.16.5

### Patchouli version

1.16.4-53.2

### Modloader version

Forge 36.2.20

### The latest.log file

https://gist.github.com/ArachKnightt/4140731384393873a610822b1cef1d5d

### Issue description

![issuereport](https://user-images.githubusercontent.com/103902870/165019458-b6d313f5-37ad-48ad-bc38-3516854bc19e.PNG)

When I startup 1.16.5 forge 36.2.20 everything works fine. However, I am trying to play on my Oculus and every time I try to startup  Vivecraft-1.16.5-jrbudda-7-8b-forge the game crashes after trying to load my mods with this error code. I figured out it was this mod causing the crash by removing it from my mods folder and starting up Vivecraft again. Without patchouli in the folder it starts and runs but I need it for ars nouveau. Essentially there is a problem when trying to run this mod through Vivecraft.

**Comment by williewillus** [comment]
Optifine is not supported (and thus vivecraft by extension). It simply does too many rendering hacks.
