### ISSUE TITLE
Mixin Crash on Startup 

### ISSUE THREAD

**Issue by Floofle** [VazkiiMods/Patchouli#543]
### Mod loader

Forge

### Minecraft version

1.18.2

### Patchouli version

1.18.2-68

### Modloader version

Forge 40.1.25/40.1.0

### The latest.log file

https://pastebin.com/UzCLCsrN

### Issue description

Patchouli crashes on startup, see log (debug.log and latest.log provided, no crash report is generated). Reproducible with only patchouli and autoreglib (1.7-53)installed.  

### Steps to reproduce

1) Install Patchouli 1.18.2-68, AutoRegLib 1.7-53
2) Attempt to launch MC

Tested on both Forge 40.1.0 and 40.1.25. 
Happy to provide more info if needed.

**Comment by agentwolf88** [comment]
Same

**Comment by morsmores** [comment]
Likewise

**Comment by Athos-E** [comment]
Same problem, if I downgrade to 67 it works just fine (mine was on forge 40.1.20)

**Comment by Cicopath** [comment]
I'm getting a similar crash with Patchouli on startup with 1.18.2-68. I keep getting Exit Code 1.

**Comment by Warhand** [comment]
Can confirm, same error happens for me too.

**Comment by slimeyena** [comment]
Just wanted to add, I have a remarkably similar issue. However it still persists _without_ patchouli, however, downgrading patchouli from 68 to 67 changes the severity of the crash from before minecraft loads, to after. (if that makes sense?)

**Comment by slimeyena** [comment]
> Just wanted to add, I have a remarkably similar issue. However it still persists _without_ patchouli, however, downgrading patchouli from 68 to 67 changes the severity of the crash from before minecraft loads, to after. (if that makes sense?)

downgrading Forge version to 40.1.20 from 40.1.25 and downgrading patchouli to 67 allows the game to launch and open a world successfully

**Comment by williewillus** [comment]
pulled the release for now. Please downgrade.

@slimeyena that sounds unrelated. Please post in #help on Discord with a crash log
