### ISSUE TITLE
Apparently cannot link to a category

### ISSUE THREAD

**Issue by aaronhowser1** [VazkiiMods/Patchouli#545]
### Mod loader

Forge

### Minecraft version

1.18.2

### Patchouli version

Patchouli-1.18.2-67

### Modloader version

Forge 40.1.23

### The latest.log file

Too big, file below

### Issue description

I have a page:

```js
        {
            "type":"patchouli:quest",
            "trigger":"plexiglassmountain:stretch_goals/flight",
            "text":"Make one of the items listed in the $(l:patchouli:game_mechanics/flight)Flight$() category (that isn't a vehicle)."
        }
```

which should be linking to the category here, as I understand it:
![image](https://user-images.githubusercontent.com/15698722/170898266-334a3a44-f2a4-41c3-9938-9464fe63576c.png)

However, it doesn't
![image](https://user-images.githubusercontent.com/15698722/170898328-ff7a3375-1507-4c5c-bcba-3d32ef589b78.png)

It should be taking me here:
![image](https://user-images.githubusercontent.com/15698722/170898414-5b40c732-370d-4acd-aa05-0d25bf50a1d9.png)

If I make it link to `patchouli:game_mechanics/flight/angel_ring`, *that* does work, so I don't know what I'm doing wrong.

### Other information
[latest.log](https://github.com/VazkiiMods/Patchouli/files/8794616/latest.log)

**Comment by williewillus** [comment]
this was added in version 68+ (69 due to a hotfix), try with that

**Comment by aaronhowser1** [comment]
My bad, that totally worked. Should have tried that to begin with, sorry

**Comment by williewillus** [comment]
No worries

**Comment by Ski-z** [comment]
Is this a known issue in 1.12.2? Having serious trouble linking within the book.

**Comment by williewillus** [comment]
That feature does not exist in 1.12
