### ISSUE TITLE
Version string reads "NONE" or "0.0NONE"

### ISSUE THREAD

**Issue by hjake123** [VazkiiMods/Patchouli#546]
### Mod loader

Forge

### Minecraft version

1.18.2

### Patchouli version

1.18.2-69

### Modloader version

Forge 40.1.25

### Modpack info

Custom modpack

### The latest.log file

https://paste.ee/p/I3YJR

### Issue description

The latest Patchouli version seems to be missing a the mods.toml version string from its jar.

### Steps to reproduce

1. Look at the mod in MultiMC and note the "NONE" version string
2. Look at the mod in a loaded instance's mod menu and note the "0.0NONE" version string

### Other information

I know this is an extremely tiny minor nitpick but it's probably easy to fix so I figure I might as well mention it. I can also attest that this was not the case in version 1.18.2-67.

**Comment by SkyeeeYT** [comment]
im also having the same problem ._.

its causing lots of lag spikes :(

**Comment by williewillus** [comment]
This has nothing to do with performance.

**Comment by williewillus** [comment]
Fixed in next version
