### ISSUE TITLE
no steel with assembly line machines and no crafting recepies withe jei

### ISSUE THREAD

**Issue by Destiny1231** [VazkiiMods/Patchouli#550]
### Mod loader

Forge

### Minecraft version

1.18.1

### Patchouli version

1.18.2-67

### Modloader version

40.1.20

### Modpack info

v:1.0.2b

### The latest.log file

https://pastebin.com/eDA632pj

### Issue description

i can´t craft steel it is bugt plis ignor log

**Comment by williewillus** [comment]
this is completely unrelated to Patchouli
