### ISSUE TITLE
External links should have a confirmation page with the link, like when you click one from chat

### ISSUE THREAD

**Issue by aaronhowser1** [VazkiiMods/Patchouli#551]
### Describe the feature

![image](https://user-images.githubusercontent.com/15698722/171989017-686fc6d2-f2a4-403b-97ae-f420e41c3902.png)

Clicking an external link should open this thing up, showing the URL you're going to

**Comment by Aizistral** [comment]
Nice idea. Lest people accidentally open links like https://aizistral.com/totally_not_a_scam_page.html
