### ISSUE TITLE
Please update to 1.19

### ISSUE THREAD

**Issue by skylorbeck** [VazkiiMods/Patchouli#554]
### Describe the feature

title

### Additional context

thanks

**Comment by williewillus** [comment]
Yes, we know it's out. No, we don't need a github issue bothering us about it. It'll be out when it's out, thanks.

**Comment by skylorbeck** [comment]
Alright glad I just removed the integration and pushed my update today without it. Maybe I'll get around to using it when you aren't so rude. Fuck me for wanting to use your mod and not knowing if you were working on it since you had no 1.19 branch or anything. Man I even made this not a bug so it wouldn't fuck up metrics. And I said please and thanks, and didn't give you my life story or whatever. Jesus man don't mod if it makes you unhappy to update.

**Comment by williewillus** [comment]
ok
