### ISSUE TITLE
Rendering Screen Crash

### ISSUE THREAD

**Issue by RedRedL** [VazkiiMods/Patchouli#556]
### Mod loader

Fabric

### Minecraft version

1.18.2

### Patchouli version

1.18.2-69

### Modloader version

Fabric Loader 0.14.6 - 1.18.2 + API 0.55.1+1.18.2

### The latest.log file

https://pastebin.com/vir8gc0i

### Issue description

Opening book and moving cursor causes crash.

### Steps to reproduce

1. Open book
2. Wait a few seconds

**Comment by williewillus** [comment]
Folding into #558
