### ISSUE TITLE
Trying to select a page crashes the game

### ISSUE THREAD

**Issue by Camwoodstock** [VazkiiMods/Patchouli#558]
### Mod loader

Fabric

### Minecraft version

1.18.2

### Patchouli version

1.18.2-67-FABRIC

### Modloader version

Fabric Loader 0.14.6, Fabric-api-base 0.4.4+d7c144a860

### The latest.log file

https://pastebin.com/raw/YB80Dv4v

### Issue description

Trying to open a book will seemingly randomly (at a high likelyhood) cause the game to crash upon opening or closing a given page.

### Steps to reproduce

1. Open a book
2. Try to navigate to a page

### Other information

The game crashed whilst rendering screen
Error: java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because "stack" is null
Exit Code: -1

**Comment by williewillus** [comment]
Try on the latest version and try to reduce the set of mods. This looks like a conflict because I see a non-Patchouli mixin in the stacktrace.

**Comment by fellock** [comment]
The conflicting mod seems to be **TooltipRareness** - found it in every crash log related to this case, and disabling it fixed the issue for me.
