### ISSUE TITLE
Minecraft crashes upon hitting the "e" Key

### ISSUE THREAD

**Issue by Sabbatha** [VazkiiMods/Patchouli#562]
### Mod loader

Forge

### Minecraft version

1.18.2

### Patchouli version

1.18.2.69

### Modloader version

40.1.31

### Modpack info

Plexiglass Mountain

### The latest.log file

https://pastebin.com/ZNWV1zCf and 

### Issue description

Opened Akashic tome
Chose Tinkering Encyclopedia
Closed Encyclopedia
Hit 'E" key to open inventory now crashes my game. 

### Other information

TConstruct-1.18.2-3.5.0.17.jar 
AkashicTome-1.5-20.jar

**Comment by williewillus** [comment]
Should be improved in 71+
