### ISSUE TITLE
[1.19] Artifact pulled from Maven has no @Mod class (Forge)

### ISSUE THREAD

**Issue by desht** [VazkiiMods/Patchouli#563]
### Mod loader

Forge

### Minecraft version

1.19

### Patchouli version

1.19-72

### Modloader version

Forge 41.0.38

### The latest.log file

n/a - no log messages

### Issue description

I'm using the blamejared maven to pull in Patchouli as a compile & runtime dependency, and while this works for compilation, Patchouli does not appear as a mod in the development workspace, since the https://maven.blamejared.com/vazkii/patchouli/Patchouli-xplat/1.19-72/Patchouli-xplat-1.19-72.jar artifact contains no class annotated with `@Mod`.  Which makes it difficult to test my mod's book...

While I can work around this by pulling the released JAR from Curseforge via cursemaven (or by putting a downloaded copy into a local flatDir repo) , I feel like this isn't the best way... is it intentional that the Maven artifact isn't actually a Forge mod, or is there something I need to do in 1.19 that I wasn't doing in earlier Minecraft versions?

### Steps to reproduce

n/a

**Comment by williewillus** [comment]
Patchouli-xplat is the xplat artifact for multiloader projects. To depend on the full forge project, use the forge artifact. This didn't change between 1.18 and 1.19

**Comment by williewillus** [comment]
^
