### ISSUE TITLE
Patchouli books dont open on rightclick

### ISSUE THREAD

**Issue by morvun** [VazkiiMods/Patchouli#564]
### Mod loader

Fabric

### Minecraft version

1.19.0

### Patchouli version

Patchouli-1.19-72-FABRIC

### Modloader version

fabric-api-0.56.1+1.19 / Loader 0.14.8 - 1.19

### The latest.log file

https://pastebin.com/tTLpzcNR

### Issue description

Patchouli books don't open on rightclick. Tested with multiple mods, like croptopia and better-end.
I also deleted after the first accurence all config files and generated new ones. Happends on every save.

**Comment by DiscoDude96** [comment]
Not just you... me too. I hope I relieved you by letting you know you're not the only one. Hope it gets fixed, waited a long ass time for it to release on  1.19.

**Comment by williewillus** [comment]
probably #566, moving there
