### ISSUE TITLE
Mod loading error, sided-setup event setup phase

### ISSUE THREAD

**Issue by vsumpi** [VazkiiMods/Patchouli#571]
### Mod loader

Forge

### Minecraft version

1.16.5

### Patchouli version

1.16.4-53.3

### Modloader version

Forge: 36.2.26

### Modpack info

https://forum.feed-the-beast.com/threads/ftb-ultimate-anniversary-edition-release.305139/

### The latest.log file

https://gist.github.com/sumpiii8/5e9823b454d14902eea3fa922f9e4db0

### Issue description

Mod loading when starting FTB Ultimate: Anniversary Edition.
Cant start. Re-install failed.

**Comment by williewillus** [comment]
Your `.minecraft/patchouli_data.json` file got corrupted, delete it and restart.
