### ISSUE TITLE
Patchouli Books don't generate in game

### ISSUE THREAD

**Issue by Youhadabadday** [VazkiiMods/Patchouli#573]
### Mod loader

Forge

### Minecraft version

1.18.2

### Patchouli version

1.18.2-67

### Modloader version

Forge 40.1.19

### The latest.log file

Not Applicable, because it happens every single time I try to use the mod in general.

### Issue description

Patchouli's books simply do not spawn in the game at all. They don't appear in my inventory, they don't appear in any creative menus, they just don't appear at all. This issue has been present every single time I try to use the mod, even before the version I'm currently using, and I have no idea what could be causing it.

### Steps to reproduce

Not Applicable, because it happens every single time I try to use the mod in general.

### Other information

Not Applicable, because it happens every single time I try to use the mod in general, even with other mods.

**Comment by williewillus** [comment]
Patchouli does not add any books on its own. Other mods and modpacks do that. I don't understand what your report is, because plenty of mods use Patchouli just fine.
