### ISSUE TITLE
Crashes on latest Forge 1.19

### ISSUE THREAD

**Issue by Gamemassa** [VazkiiMods/Patchouli#584]
### Mod loader

Forge

### Minecraft version

1.19

### Patchouli version

1.19-73

### Modloader version

41.0.85

### The latest.log file

https://gist.github.com/Gamemassa/b21d1a3b9940c4ad0bf507bb618e23aa

### Issue description

I loaded MC with the latest versions of Forge and Patchouli. Patchouli encountered a ForgeModelBakery error. I've attached the crash report.

[crash-2022-07-09_17.47.40-fml.txt](https://github.com/VazkiiMods/Patchouli/files/9077985/crash-2022-07-09_17.47.40-fml.txt)

**Comment by williewillus** [comment]
Forge made a ton of breaking changes, the workaround for now is to use 41.0.63 or earlier.

**Comment by Gamemassa** [comment]
Yeah, that's what I've been hearing in a lot of places, but it didn't look like anyone else had reported this issue with Patchouli yet, so I thought I'd be the first just to make sure you guys were aware.

**Comment by Gamemassa** [comment]
Patchouli version 74 appears to have fixed the issue.
