### ISSUE TITLE
Patchouli not Working

### ISSUE THREAD

**Issue by mindoesthingz** [VazkiiMods/Patchouli#591]
### Mod loader

Fabric

### Minecraft version

1.19

### Patchouli version

1.18.2

### Modloader version

Fabric Loader-0.14.8+1.19; Fabric API-0.56.0+1.19

### The latest.log file

N/A

### Issue description

Whenever I have patchouli downloaded with everything in order as it should be, it still does not work. When i make the croptopia book, it cannot be opened, and says "Patchouli is not installed" when it is. Ive tried patchouli 1.17, 1.18.1 and 1.18.2, but the same issue is happening. 

### Steps to reproduce

n/a

### Other information

Fabric API is placed in the mods folder, i was told by the server im in to put it that way.

**Comment by williewillus** [comment]
```
Minecraft version

1.19
Patchouli version

1.18.2
```

what does this mean? What *exact* version of Patchouli are you trying?

**Comment by mindoesthingz** [comment]
I'm trying 1.19 (sorry for the wrong information)
