### ISSUE TITLE
Patchouli doesn't work

### ISSUE THREAD

**Issue by BurakHatip** [VazkiiMods/Patchouli#596]
### Mod loader

Forge

### Minecraft version

1.19.1

### Patchouli version

1.19-75

### Modloader version

Forge 1.19.1

### The latest.log file

https://mclo.gs/exisuAv

### Issue description

I downloaded this mod and when I try to join my aternos server with my friend, it says patchouly doesnt exist but we already have same version, I deleted patchouli and it said world couldn't start because this world saved with patchouli and it says download again and I did but nothing changed pls help

**Comment by williewillus** [comment]
You need it on the client as well.

**Comment by williewillus** [comment]
Please visit #help on Discord for more immediate help.
