### ISSUE TITLE
Patchouli crashes with Farmer's Delight

### ISSUE THREAD

**Issue by MalacoX** [VazkiiMods/Patchouli#598]
### Mod loader

Forge

### Minecraft version

1.18,2

### Patchouli version

 Patchouli-1.18.2-71.1.jar

### Modloader version

Forge - 40.1.51+

### Modpack info

I don't have it uploaded but I am making one, and this is a big problem I have and am hoping is fixed.

### The latest.log file

https://pastebin.com/rweBufWW

### Issue description

So I was making a regular mod-pack for me and my friends, as usual, the catch is when I try loading the mod it doesn't work at all
all it does is crashes as soon as I press play I traced the mod (Patchouli) not working with (Farmer's Delight) I really want this fixed since farmer's delight is one of the best cooking mods out there and I really hope this isn't a big issue.

### Steps to reproduce

1. Download Patchouli and Farmer's Delight
2. Run Minecraft

### Other information

Of course, I was testing this with a few extra mods but I am confident it is from Farmer's Delight and Patchouli

**Comment by williewillus** [comment]
Please read the error message the game shows you on startup:
net.minecraftforge.fml.ModLoadingException: Mod patchouli requires forge 40.1.51 or above
