### ISSUE TITLE
ctd when reading books 75 and 74

### ISSUE THREAD

**Issue by ZolElle** [VazkiiMods/Patchouli#600]
### Mod loader

Forge

### Minecraft version

1.19

### Patchouli version

1.19-75 1.19-74 1..19-73

### Modloader version

41.0.110

### The latest.log file

https://pastebin.com/PmETygXG

### Issue description

game crashes when reading a patchouli book in both version 75 ad 74

### Steps to reproduce

read patchouli book

### Other information

version 73 also fails to load correctly

**Comment by williewillus** [comment]
Should work now with latest Patchouli and forge 1.19.2
