### ISSUE TITLE
Freeze and unfinished game crash when loading world

### ISSUE THREAD

**Issue by Chaos02** [VazkiiMods/Patchouli#601]
### Mod loader

Forge

### Minecraft version

1.18.2

### Patchouli version

1.18.2-71.1

### Modloader version

forge-40.1.73

### Modpack info

https://www.curseforge.com/minecraft/modpacks/techattack

### The latest.log file

https://pastebin.com/GNPHRQt3

### Issue description

Spontaneous game freeze on game load.
Seems to persist as of now but sometimes doesn't do it.

### Steps to reproduce

Load up Modpack
Enter World
Freeze

### Other information

seems to be in correlation with issue https://github.com/DynamicTreesTeam/DynamicTrees/issues/713

**Comment by williewillus** [comment]
So there's two issues here, one is Dynamic Trees' book is malformed (there is a `sortnum` with a string value instead of integer), and second Dynamic Trees' worldgen is causing the actual crash. Closing this out since neither issue is addressable by Patchouli.

**Comment by Chaos02** [comment]
Thank you for telling me, I will try to help fix this issue on their end!
