### ISSUE TITLE
Crash when searcing index of a book and typing the letter R

### ISSUE THREAD

**Issue by MuteTiefling** [VazkiiMods/Patchouli#610]
### Mod loader

Forge

### Minecraft version

1.19.2

### Patchouli version

1.19.2-76

### Modloader version

43.1.16

### Modpack info

Enigmatica 9 InDev

### The latest.log file

https://gist.github.com/MuteTiefling/6dc17a41b7daf24ba100bef1c64553fc

### Issue description

The game crashes when searching the Index of a Patchouli book and typing the letter R. 

### Steps to reproduce

1. Open a Patchouli Book
2. Click the Index
3. Start typing a word with R in it, such as `thread`
4. Crash

**Comment by williewillus** [comment]
Looks like it's a bug in the JEI integration
