### ISSUE TITLE
Could not find vazkii.patchouli:Patchouli:1.18.2-71.1_mapped_official_1.18.2.

### ISSUE THREAD

**Issue by Luppyn** [VazkiiMods/Patchouli#612]
### Mod loader

Forge

### Minecraft version

1.18.2

### Patchouli version

71.1

### Modloader version

Forge 40.1.80

### The latest.log file

https://pastebin.com/raw/r8BHfE2b

### Issue description

I'm using Mcreator to improve my modmaker skills and don't undertand what is wrong. 

Here is my [build.gradle](https://pastebin.com/mS3diYDG)
Here is my [gradle.properties](https://pastebin.com/kPAchjLz)
And [here ](https://i.imgur.com/W4SB8IL.png) is my problem.

### Steps to reproduce

1. Install Mcreator 2022.2
2. Install [ShadowAPIs](https://mcreator.net/plugin/84967/shadowsapis) plugin on version 1.0.2.1
3. Follow [this ](https://www.youtube.com/watch?v=xGHHgW_-NzY)tutorial until `08:43`, but change the old values to the newest (mcVersion 1.18.2/ patchouliVersion 71.1/ forgeVersion 40.1.80)
4. Try open the client on Mcreator and get an error!

### Other information

I put my log only because is obligatory.

**Comment by williewillus** [comment]
Please visit MCreator support channels instead. I'm not familiar at all with how their environment works and can't offer any help. From a brief glance, the repository and dep strings for Patchouli seem to be ok, so it's probably an issue on the MCreator side.
