### ISSUE TITLE
world loading freeze on 100%

### ISSUE THREAD

**Issue by ZaksenCode** [VazkiiMods/Patchouli#619]
### Mod loader

Forge

### Minecraft version

1.16.5

### Patchouli version

1.16-42

### Modloader version

36.2.34

### The latest.log file

https://pastebin.com/RtZ6BdYk

### Issue description

when i try to open world it freeze on 100% and noting else.

### Steps to reproduce

1.start minecraft (from IntelliJ IDEA)
2.open world or create a new one

**Comment by ChrisClickbait** [comment]
Having this same problem on 1.18.2 with version 1.8.2-71.1

**Comment by ZaksenCode** [comment]
> 
have any fixes?

**Comment by williewillus** [comment]
@CosmicChrisss please report separately. Major versions of mc differ drastically so it's exceedingly unlikely it's the same underlying issue.

@zaDR0tic you are using an extremely old Patchouli 1.16.2 version on 1.16.5. Please update to the latest version (at the time of writing it should be [Patchouli-1.16.4-53.3.jar](https://www.curseforge.com/minecraft/mc-mods/patchouli/files/3847029)

**Comment by ZaksenCode** [comment]
> @zaDR0tic you are using an extremely old Patchouli 1.16.2 version on 1.16.5. Please update to the latest version (at the time of writing it should be [Patchouli-1.16.4-53.3.jar](https://www.curseforge.com/minecraft/mc-mods/patchouli/files/3847029)

new version doesn't fix problem

**Comment by williewillus** [comment]
post new logs.

**Comment by williewillus** [comment]
Also, I see that you're in the dev environment. Please visit #patchouli_support or #vm_mods on Discord, or IRC to get realtime help.

**Comment by ZaksenCode** [comment]
yes, i find solve, i just need use genIntellijRuns one more time.
