### ISSUE TITLE
Java language version problem

### ISSUE THREAD

**Issue by KaelaniRevyruun** [VazkiiMods/Patchouli#620]
### Mod loader

Forge

### Minecraft version

1.18.2

### Patchouli version

1.18.2-71.1

### Modloader version

forge-1.18-38.0.17

### The latest.log file

https://gist.github.com/KaelaniRevyruun/63e250e90cb792a01c363cfdcadbe119

### Issue description

Upon starting load, the game hits the outdated version of javafml (specifically 38), and proceeds to crash hard enough that the entire SE binary process cannot be reinitialised unless the entire computer is rebooted.

I have tried with the following ram levels (thinking it was a ram problem): 7GB, 11GB, 16GB

After a google search I found a solution that states that the javafml version 38 build of patchouli is apparently for 1.18.1, but the most recent build on curseforge for 1.18 (showing 1.18.2) gives javafml version 38. 

### Steps to reproduce

step 1: download and install forge 1.18 version 38.0.17 on fresh vanilla launcher
step 2: run forge build for the first time (to create mods folder)
step 3: add mod files as listed in latest.log
step 4: Attempt to launch game with mods included.
step 5: frown in confusion as 30 seconds after launch, the game crashes and takes the Java SE Platform Binary with it until computer OS restart.

**Comment by williewillus** [comment]
You have forge for minecraft 1.18.0 installed. If you read your log, you're trying to run a ton of 1.18.2 mods on 1.18.0. That won't fly, install 1.18.2 and forge 40.xx, this isn't a Patchouli bug.

**Comment by KaelaniRevyruun** [comment]
Ok that is kinda messed up then... Just looked a little more closely at the forge download, and looks like cos I didn't specify .2 in the google search, I got given the lowest forge iteration >.<

**Comment by williewillus** [comment]
Yeah, you have to be careful with the minor versions.
