### ISSUE TITLE
Mod File Patchouli-1.19.2-77.jar needs language provider javafml:43 or above to load

### ISSUE THREAD

**Issue by efa** [VazkiiMods/Patchouli#622]
### Mod loader

Forge

### Minecraft version

1.19.2

### Patchouli version

1.19.2-77

### Modloader version

forge 41.0.99

### The latest.log file

https://pastebin.com/BcYWwZDr

### Issue description

Debian 11 bullseye
Minecraft 1.19.2 with forge 41.0.99
In the launcher, pressing button Start/Play, after Mojang screen I got this error:

Failure message: Mod File Patchouli-1.19.2-77.jar needs language provider javafml:43 or above to load
		We have found 41

### Steps to reproduce

In the launcher, pressing button Start/Play

**Comment by williewillus** [comment]
Forge 41.xx is for 1.19.0, the latest Forge is 43.xx for 1.19.2. Try updating? I should have set it in the manifest, sorry.

**Comment by efa** [comment]
upgraded, works. Thank you, I missed the minor version
