### ISSUE TITLE
1.19.3 release

### ISSUE THREAD

**Issue by tambry** [VazkiiMods/Patchouli#632]
### Describe the feature

It would be nice to have a release for 1.19.3 since most other dependencies and mods have already released theirs.

**Comment by GoldenDei** [comment]
Yes can you please release the mod for 19.3?

**Comment by Ayutac** [comment]
I can help if there is help needed for the port :/

**Comment by williewillus** [comment]
No help needed, I'm just on a short break til the end of January. It will be out then.

**Comment by Wraithypooo** [comment]
I can see someone got their hands on a 1.19.3 fabric..... is 1.19.3 forge out yet? (I can't finde either on Curse or modrinth)

**Comment by williewillus** [comment]
Out as of Feb 10
