### ISSUE TITLE
1.19.3 build crash upon game launch

### ISSUE THREAD

**Issue by EntangledLabs** [VazkiiMods/Patchouli#641]
### Mod loader

Fabric

### Minecraft version

1.19.3

### Patchouli version

1.19.3-78-FABRIC-20230126.010519-1

### Modloader version

Fabric Loader 0.14.13-1.19.3 + API 0.73.2+1.19.3

### The latest.log file

https://pastebin.com/yd4BnjBL

### Issue description

Note: this version of Patchouli somehow works with the exact same Fabric loader/API serverside

Launching Minecraft with Fabric ends up with Exit Code 1. Seems to be a problem with the mixins?

**Comment by williewillus** [comment]
@Minecraftschurli can you take a look? I think you modified the mixin here for the 1.19.3 update

**Comment by williewillus** [comment]
@EntangledLabs can you repro without other mods?

**Comment by Minecraftschurli** [comment]
weird I tested it in dev and fabric as well as forge started fine. I'll have a look

**Comment by Minecraftschurli** [comment]
hmm... just tested and it works in patchouli dev

**Comment by EntangledLabs** [comment]
I just tested it and it works - i'm going to start mercilessly going through the mods to find the incompatibility lol

**Comment by EntangledLabs** [comment]
Interesting - the game is now stuck in a boot loop

In fact, it generated a 500 MB log file that i cant copy paste

**Comment by EntangledLabs** [comment]
https://pastebin.com/iiqhzmsG

It seems to be somewhat repetitive - I think its trying to go through every single block in the game, but it keeps throwing exceptions of the same sort

Edit: that's only the bottom few hundred lines - the file goes to 3.6 million

**Comment by Minecraftschurli** [comment]
it seems like something breaks the model bakery which causes the same error on most (if not all) models
