### ISSUE TITLE
I can't open the book in my server

### ISSUE THREAD

**Issue by rafa08** [VazkiiMods/Patchouli#643]
### Mod loader

Forge

### Minecraft version

1.18.2

### Patchouli version

1.18.2-71.1

### Modloader version

Forge - 40.1.93

### The latest.log file

https://mclo.gs/rv26rZ3

### Issue description

Hello friends, I have the following problem with Patchouli Mod. Locally from my computer I can open my book perfectly and it works, but when I try it on my Aternos server in multiplayer, I can't open it by right-clicking. I would like to know if on the server side I am adding it in the wrong path or what is the correct path to add the book.json on the server.

Thank you very much for anything you can help me. Please.

**Comment by williewillus** [comment]
If you can show a repository with your book in it that would assist in
debugging a lot.

**Comment by Unlikekillakay** [comment]
Im having the same issue. The book is there in the server but when i right click it doesn't open and i get no message anywhere on why it doesn't open up.

**Comment by rafa08** [comment]
Hello Friends, I was able to solve the problem. What happened was that in the Aternos Server it does not allow creating the patchouli_books folder in the home path. I had to choose a paid server. On the new server I created my book in the home path and everything worked perfectly. Thank you also for everything!
