### ISSUE TITLE
com.google.gson.JsonSyntaxException: Missing name, expected to find a string

### ISSUE THREAD

**Issue by xFirefalconx** [VazkiiMods/Patchouli#644]
### Mod loader

Forge

### Minecraft version

1.18.2

### Patchouli version

Patchouli-1.18.2-71.1.jar

### Modloader version

Forge 40.2.0

### Modpack info

WIP self made modpack (190 mods). I can't post any links as of now, still waiting for a mod to release before I can attempt to publish it.. 

### The latest.log file

https://gist.github.com/xFirefalconx/2ddbe2b6acff223c0a0adc0ed57fa274

### Issue description

I don't know what is expected and what is not to be expected but I found this line in my latest log while trying to find the cause for a resourcepack issue (can't load any worlds or create new ones rn). This can be unrelated but maybe you want to fix this in case it causes issues elsewhere. I'm going through the log chronologically right now.

I have an issue with asticorcarts right now so there might be linked issues that don't concern you. 

`15:41:12.845
patchouli
Worker-Main8
Failed to load book dynamictreesplus:guide defined by mod dynamictreesplus, skipping
com.google.gson.JsonSyntaxException: Missing name, expected to find a string
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.util.GsonHelper.m_13906_(GsonHelper.java:112)
	at TRANSFORMER/patchouli@1.18.2-71.1/vazkii.patchouli.common.book.Book.<init>(Book.java:122)
	at TRANSFORMER/patchouli@1.18.2-71.1/vazkii.patchouli.common.book.BookRegistry.loadBook(BookRegistry.java:116)
	at TRANSFORMER/patchouli@1.18.2-71.1/vazkii.patchouli.common.book.BookRegistry.lambda$init$3(BookRegistry.java:76)
	at java.base/java.util.HashMap.forEach(HashMap.java:1421)
	at TRANSFORMER/patchouli@1.18.2-71.1/vazkii.patchouli.common.book.BookRegistry.init(BookRegistry.java:71)
	at TRANSFORMER/patchouli@1.18.2-71.1/vazkii.patchouli.forge.common.ForgeModInitializer.onInitialize(ForgeModInitializer.java:59)
	at net.minecraftforge.eventbus.ASMEventHandler_746_ForgeModInitializer_onInitialize_FMLCommonSetupEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at LAYER PLUGIN/javafmllanguage@1.18.2-40.2.0/net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106)
	at LAYER PLUGIN/fmlcore@1.18.2-40.2.0/net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)`

### Steps to reproduce

Add these mods mentioned in the log. 
I have 190, it might not be all of them linked to this issue. 
My hunch is that it's dynamic trees plus. 

### Other information

Important info, some mods have non fitting file names. If you can't find them let me know the file name and I'll find you the mod page. 

supplementaries-1.18.2-1.5.16.jar
VendingMachine-1.18.2-1.0.8.jar
wildberries-1.1.2[forge-1.18.2].jar
jei-1.18.2-9.7.1.255.jar
JEIEnchantmentInfo-1.17.1-2.0.0.jar
ChunkByChunk-forge-1.18.2-1.12.4.jar
ManyIdeasDoors-1.18.2-1.2.0.jar
ManyIdeasCore-1.18.2-1.4.0.jar
RecipesLibrary-1.18.2-2.0.0.jar
hauntedharvest-1.18.2-1.7.7.jar
untamedwilds-1.18.2-2.3.0.jar
citadel-1.11.3-1.18.2.jar
towns_and_towers_forge-1.10.0.1+1.18.2.jar
Beyond-Earth-1.18.2-6.2.jar
astikorcarts-1.18.2-1.1.2.jar
balm-3.2.2+0.jar
BambooEverything-forge-1.3.8-build.45+mc1.18.2.jar
BeeFix-1.18-1.0.7.jar
Beekeeper-1.18.2-1.0.5.jar
BetterCompatibilityChecker-1.1.21-build.48+mc1.18.2.jar
betterspawnercontrol-1.18.2-4.0.jar
BetterThirdPerson-Forge-1.18.2-1.9.0.jar
biomespawnpoint-1.18.2-2.0.jar
Bookshelf-Forge-1.18.2-13.2.52.jar
ChunkByChunk-forge-1.18.2-1.12.2.jar
collective-1.18.2-6.43.jar
Disenchanting-forge-1.18.2-2.2.2.jar
DynamicTrees-1.18.2-0.11.0-Beta5.jar
EnchantmentDescriptions-Forge-1.18.2-10.0.12.jar
geckolib-forge-1.18-3.0.57.jar
keepmysoiltilled-1.18.2-2.0.jar
Level-One-MC1.18.2-v1.6.0.jar
mcw-bridges-2.0.6-mc1.18.2forge.jar
mcw-roofs-2.2.2-mc1.18.2forge.jar
mcw-windows-2.1.1-mc1.18.2forge.jar
nocube's_villagers_sell_animals_1.1.4_forge_1.18.2.jar
passiveendermen-1.18.2-4.1.jar
Pehkui-3.6.3+1.18.2-forge.jar
player-animation-lib-forge-0.4.2+1.18.jar
so_many_enchants-1.7.1 (1.18).jar
sophisticatedbackpacks-1.18.2-3.18.40.777.jar
sophisticatedcore-1.18.2-0.5.37.202.jar
villagebellrecipe-1.18.2-3.0.jar
villagespawnpoint-1.18.2-4.0.jar
benched-1.2.2-forge-mc1.18.jar
create-1.18.2-0.5.0.i.jar
flywheel-forge-1.18.2-0.6.8.a.jar
mcwfencesbop-1.18.2-1.4.jar
mcw-fences-1.0.7-mc1.18.2forge.jar
create_food-1.18.2.jar
ArtisticCraft v0.16.1-1.18.2.jar
Copper Armory Remastered 1.2.1 1.18.2.jar
TexelsPaintings-forge-1.18.2-5.1.0.jar
VariantCraftingTables-1.18.2-1.7.0_1.jar
RedstoneExtras-1.18-1.0.11.jar
Tips-Forge-1.18.2-5.0.11.jar
WhatTheBucket-Forge-1.18.2-4.0.1.jar
MemorySweep-1.18.2-0.8.jar
corn_delight-1.0.6-1.18.2.jar
mmlib-1.2.0-1.18.2.jar
waystone_towers-1.18.2-FORGE-1.0.9.jar
hole_filler_mod_1.2.5-mc_1.18.1-forge.jar
fantasyfurniture-1.18.2-3.14.0.jar
Roads-1.18.1-1.4.0.jar
little_geode 1.18.2-1.3.0.jar
IBICF-1.4.0-build.8+mc1.18.2.jar
unordinary_basics-1.18.2-1.0.1.3.jar
manascore-1.18.2-1.0.2.0.jar
cell-lever-1.18-3.0.0.1.jar
crittersandcompanions-1.18.2-1.0.2.jar
horse_colors-1.18.2-1.8.0.jar
majrusz-library-1.18.2-3.1.0.jar
majruszs-accessories-1.18.2-1.1.3.jar
FruitTrees-1.18.2-forge-5.0.1.jar
burgermod-2.8.0-1.18.2.jar
verdure-1.18.2-1.1.3a.jar
(Forge)SimpleMango-1.18.2-1.2.0.jar
Netherited-forge-1.18.2-1.2.1.jar
atmospheric-1.18.2-4.0.0.jar
MoreCrashInfo-2.3.1.jar
realisticroads-v2.jar
sootychimneys-1.18.2-1.0.0l.jar
movingelevators-1.3.11b-forge-mc1.18.jar
NaturalDecorMod1.18IIV0.1BETA.jar
SereneShrubbery-1.18.2-1.3.0.jar
workers-1.18.2-1.5.2.jar
smoothboot(reloaded)-mc1.18.2-0.0.2.jar
Clumps-forge-1.18.2-8.0.0+17.jar
ferritecore-4.2.2-forge.jar
Regrowth-1.18.2-1.40.31.1.jar
spells_and_shields-1.18.2-1.9.2.jar
polymorph-forge-1.18.2-0.46.jar
ftbbackups2-forge-1.18.2-1.0.17.jar
polylib-forge-1801.0.2-build.13.jar
kleeslabs-forge-1.18.2-11.1.1.jar
ExNihiloSequentia-1.18.2-20221113-044349.jar
Jade-1.18.2-forge-5.2.6.jar
weaponleveling-1.18.2-1.4.3.jar
citydecor-1.1.1.jar
appleskin-forge-mc1.18.2-2.4.1.jar
Patchouli-1.18.2-71.1.jar
largemeals-1.18.2-2.0.jar
honeyexpansion-1.1.1.jar
FarmersRespite-1.18.2-1.3.0.jar
Crated_Vanilla_Foods_1.1-1.18.2.jar
MoreMobGriefingOptions-1.18.2-2.0.1.jar
SoL-Carrot-1.18.1-1.12.0.jar
forgivingvoid-forge-1.18.1-6.0.1.jar
MobCatcher-Forge-1.18.2-1.1.6.jar
ItemLocks-Forge-1.18.2-1.3.jar
GameMenuModOption-1.18-Forge-1.14.2.jar
SBM-Jukebox-1.18-1.0.4.jar
deepslate_dubble003.jar
hedgehog-1.18.2-1.1.0.jar
snowyspirit-1.18.2-1.3.2.jar
bewitchmentplus-1.18.2-14.jar
overweightfarming-1.18.2-1.6.0-forge.jar
croptopia-chocolaterie-1.1.jar
Croptopia-1.18.2-FORGE-2.1.0.jar
DynamicSurroundings-5.0.0.4.jar
Oh_The_Biomes_You'll_Go-forge-1.18.2-1.4.7.jar
torchmaster-18.1.0.jar
cookingforblockheads-forge-1.18.2-12.2.0.jar
beehive-tooltips-forge-1.4.2.jar
XPFromHarvest-1.18.2-1.2.2.jar
xptome-1.18.2-2.1.7.jar
swingthroughgrass-1.18.2-1.9.1.jar
SnowRealMagic-1.18.2-forge-4.2.3.jar
3dskinlayers-forge-1.5.2-mc1.18.2.jar
Placebo-1.18.2-6.6.6.jar
DynamicTreesPlus-1.18.2-0.1.0-Beta1.jar
DynamicTreesBOP-1.18.2-3.0.0-Beta1.jar
ChinjufuMod[1.18.2]6.2.4.jar
configured-2.0.0-1.18.2.jar
betterfoliage-3.1.4.jar
Chimes-1.1.2-1.18.2.jar
anviltooltipmod-MC1.18.2-1.0.0.jar
merenc-forge-1.18.x-v1.9.jar
FarmersDelight-1.18.2-1.2.0.jar
blueprint-1.18.2-5.5.0.jar
cloth-config-6.4.90-forge.jar
Kiwi-1.18.2-forge-6.1.3.jar
TerraBlender-forge-1.18.2-1.2.0.126.jar
Better Fishing Rods 1.0.0 - 1.18.2.jar
Book Fishing 1.0.0 - 1.18.2.jar
AkashicTome-1.5-20.jar
autoplant-1.18.2-1.0.0.jar
BadMobs-1.18.2-13.01.jar
bamboo2-1.18.1_0.4.jar
supermartijn642configlib-1.1.6-forge-mc1.18.jar
better-loading-screen-1.4.0.jar
bettermending-forge-1.2.1+1.18.2.jar
bettersafebed-1.18-forge-a.jar
BorderlessWindow-1.18-1.4.0.jar
carryon-1.18.2-1.17.0.8.jar
Controlling-forge-1.18.2-9.0+22.jar
creeperconfetti-3.11.jar
DungeonCrawl-1.18.2-2.3.10.jar
BiomesOPlenty-1.18.2-16.0.0.109-universal.jar
wooltostring-forge-1.18.2-1.0.1.jar
exoticbirds-1.18.2-1.8.0.jar
ExtendedItemInformation-4.0.2-1.18.2.jar
farmingforblockheads-forge-1.18.2-10.0.2.jar
FastLeafDecay-28.jar
guardvillagers-1.18.2.1.4.3.jar
EnderBags-1.18.1-8.0.0.jar
InfoDataPack-1.18.1-2.0.2.8.jar
JustEnoughResources-1.18.2-0.14.1.171.jar
modnametooltip-1.18.1-1.18.0.jar
moreoverlays-1.20.9-mc1.18.2.jar
MouseTweaks-forge-mc1.18-2.21.jar
NaturesCompass-1.18.2-1.9.7-forge.jar
Quark-3.2-358.jar
AutoRegLib-1.7-53.jar
skylightlanterns-1.18.2-1.0.0.jar
selene-1.18.2-1.17.9.jar
village-employment-1.18.2-1.5.1.jar
VillagersRespawn-1.18.1-1.39.0.5.jar
waystones-forge-1.18.2-10.1.0.jar
tumbleweed-1.18-0.5.4.jar.disabled
supermartijn642corelib-1.1.2-forge-mc1.18.jar
Many Advancements-1.18.2-1.4.jar
Dessertv1.2.jar
ChiselsBits-forge-1.18.2-1.2.116-universal.jar
AbsolutelyUnbreakable1.18.2-2.0.1-1.18.2.jar
itemcollectors-1.1.7-forge-mc1.18.jar
cherryblossomgrotto-0.4.5-v1.18.2.jar
architectury-4.11.89-forge.jar
Curses_and_magic_1.9_1.18.2.jar
journeymap-1.18.2-5.9.3-forge.jar
mcw-doors-1.0.8forge-mc1.18.2.jar
SHAB (1.18.2) V1.1.0.jar

**Comment by williewillus** [comment]
dynamictreesplus has a broken book.

**Comment by williewillus** [comment]
^
