### ISSUE TITLE
crash when load the world

### ISSUE THREAD

**Issue by WCOKE** [VazkiiMods/Patchouli#649]
### Mod loader

Forge

### Minecraft version

1.19.4

### Patchouli version

78

### Modloader version

Forge 45.0.40

### The latest.log file

https://gist.github.com/WCOKE/c2bd77784aa7b5219465b280d023559a#file-gistfile1-txt

### Issue description

dont know whats going on,game will crash when load or create a world,is it beacuse the mod version doesnt match the game？
i only install optifine and this mod.

**Comment by LogBomb** [comment]
Hey, I'm having the same issue as you. I just noticed Patchouli is for 1.19.3 and I'm on 1.19.4 maybe you are too? Can't find a 1.19.4 edition so I guess we need to wait

**Comment by Atroskelis** [comment]
Can confirm this, crashes on world load on 1.19.4 with patchouli 1.19.3

**Comment by williewillus** [comment]
Folding into #654
