### ISSUE TITLE
1.19.4 Update?

### ISSUE THREAD

**Issue by cmar7945** [VazkiiMods/Patchouli#654]
### Describe the feature

Any chance we can get a 1.19.4 port? Ive already been using several fabric mods that rely on patchouli for documentation that wont work. Or perhaps make the 1.19.3 version work with 1.19.4 like ive seen other mods do in some way?

**Comment by ReasonableScripts** [comment]
yes please, 1.19.4 RFtools manual doesn't work without it and if I try using patchouli 1.19.3 it crashes

**Comment by OBS3SS1ON** [comment]
x2 need 1.19.4 I can't open the new books of 1.19.4

**Comment by silversaturn** [comment]
Croptopia needs Patchouli, and while it does function without it we can't have any guide books for recipes that would make things more organized.  Croptopia updated to 1.19.4 but unfortunately Patchouli has not and makes the server not want to start with it in.. so it does break operations now.  Some mods will function despite being out of date but this is not one of them.

**Comment by sorae42** [comment]
patchouli is on 1.19.4 now (as snapshot)

**Comment by HeatSignature** [comment]
Yes please x100 such an epic framework!

**Comment by xandercreates** [comment]
> patchouli is on 1.19.4 now (as snapshot)

where?

**Comment by sorae42** [comment]
> > patchouli is on 1.19.4 now (as snapshot)
> 
> where?

check the artifacts/release page?

**Comment by williewillus** [comment]
out now
