### ISSUE TITLE
Datapack Support

### ISSUE THREAD

**Issue by mintdaniel42** [VazkiiMods/Patchouli#655]
### Describe the feature

Currently there are two ways to add content to patchouli:
1. in the /patchouli_books folder
2. in a mod in the /data/mod_id/patchouli_books folder
Why isn't it possible to do it via a datapack? I tried it and it didn't show up (/data/datapack_namespace/patchouli_books)

### Additional context

I am on 1.19.2 Fabric

**Comment by williewillus** [comment]
we actually want to go the other way, so that books are completely clientsided.
Books aren't really data, they are assets/resources.
