### ISSUE TITLE
Modified Fabulously Optimized crash.

### ISSUE THREAD

**Issue by GRKTheGreat** [VazkiiMods/Patchouli#657]
### Mod loader

Fabric

### Minecraft version

1.19.4

### Patchouli version

Patchouli-1.19.3-78-FABRIC.jar

### Modloader version

fabric 0.14.21

### The latest.log file

https://paste.ee/p/t09sh

### Issue description

NoSuchMethodError: 'net.minecraft.client.resource.language.LanguageDefinition net.minecraft.client.resource.language.LanguageManager.getLanguage()'
at

ClientBookRegistry#reload (Line 62)

at

ClientAdvancements#onClientPacket (Line 34)

at

ClientAdvancementManager#handler$gfa000$patchouli$onSync (Line 1017)

at

ClientAdvancementManager#onAdvancements (Line 57)

at

ClientPlayNetworkHandler#onAdvancements (Line 1392)

at

AdvancementUpdateS2CPacket#apply (Line 51)

at

AdvancementUpdateS2CPacket#apply (Line 16)

at

NetworkThreadUtils#method_11072 (Line 22)

at

ThreadExecutor#executeTask (Line 156)

at

ReentrantThreadExecutor#executeTask (Line 23)

at

ThreadExecutor#runTask (Line 130)

at

ThreadExecutor#runTasks (Line 115)

at

MinecraftClient#render (Line 1174)

at

MinecraftClient#run (Line 801)

at

Main#main (Line 237)

at

MinecraftGameProvider#launch (Line 468)

at

Knot#launch (Line 74)

at

KnotClient#main (Line 23)
[Fabulously Optimized CUSTOMIZED-4.10.3.zip]

File : (https://github.com/VazkiiMods/Patchouli/files/11713728/Fabulously.Optimized.CUSTOMIZED-4.10.3.zip)

### Steps to reproduce

1. launch.
2. (Don't know if it works with new worlds) Load world.
3. crash.

### Other information

If the crash does not happen on new world creation/load Message me for my world file.

**Comment by williewillus** [comment]
It doesn't run on 1.19.4 yet. Soon.
