### ISSUE TITLE
Causes crash when viewing a locked page.

### ISSUE THREAD

**Issue by Ironnoob73** [VazkiiMods/Patchouli#658]
### Mod loader

Forge

### Minecraft version

1.12.2

### Patchouli version

1.0-23.6

### Modloader version

Forge: 14.23.5.2860

### The latest.log file

https://gist.github.com/Ironnoob73/34c3cecb38ee439e567d9eea6c1352ba

### Issue description

When attempting to read a locked page in any way, it causes the game to crash. Reading methods include: shift + right-click a block which has a page in the book; Open the book in a world that has unlocked the corresponding page, then switch to the world that does not unlock that page, then open the book.

### Steps to reproduce

1. Unlock a page with achievements
2. Open that page
3. Exit the world and open a world that has not yet been unlocked for that page
4. Open the book

### Other information

This issue doesn't seem to be happening just with 1.12.2, other versions have similar issues. Is it possible to jump directly to the beginning of the book when the player tries to read a locked page?

**Comment by williewillus** [comment]
We don't have the resources to support 1.12 any more.
A workaround for this is to delete the patchouli_data JSON file from the .minecraft directory of the instance. This clears the "last page viewed" save data and should reset the book to its initial state.
