### ISSUE TITLE
So 1.19.4 isn't 1.19.3

### ISSUE THREAD

**Issue by Sapfirelynx** [VazkiiMods/Patchouli#660]
### Mod loader

Fabric

### Minecraft version

1.19.4

### Patchouli version

79

### Modloader version

0.14.21

### The latest.log file

n/a

### Issue description

This might be a thing that needs to be reported on github.  I don't know if it was intentional or not.  My minecraft said that Paladin couldn't connect with Patchouli which I thought was odd since it was listed for 1.19.4, so I turned it into a zip, popped it into vs code only to see it was still coded for 1.19.3.
![Oops](https://github.com/VazkiiMods/Patchouli/assets/87036420/bc1fd9d0-e1d5-4eac-b531-9ece75a36571)

### Other information

Just thought you should know.

**Comment by williewillus** [comment]
Sapfirelynx ***@***.***> writes:

> This might be a thing that needs to be reported on github.  I don't know if it was
> intentional or not.  My minecraft said that Paladin couldn't connect with Patchouli which
> I thought was odd since it was listed for 1.19.4, so I turned it into a zip, popped it
> into vs code only to see it was still coded for 1.19.3.
> ![Oops](https://github.com/VazkiiMods/Patchouli/assets/87036420/bc1fd9d0-e1d5-4eac-b531-9ece75a36571)
>

This is benign. Those strings say ">=1.19.3", and I just forgot to
update them to say ">=1.19.4". The mod might crash weirdly on startup
instead of Fabric Loader showing the missing dependency message if you
use it on 1.19.3, but otherwise it should work on 1.19.4.

If there's another 1.19.4 build, I'll fix it.

**Comment by Sapfirelynx** [comment]
I was trying it on 1.19.4 and it wasn't working but it did work for 1.19.3

**Comment by williewillus** [comment]
I cannot reproduce this at all. 1.19.4-79 in a fresh 1.19.4 instance with the latest Fabric API loads perfectly fine.
