### ISSUE TITLE
Patchouli is showing up in 1.20 with a 1.19.4 version mod

### ISSUE THREAD

**Issue by Devilswarchild** [VazkiiMods/Patchouli#662]
### Mod loader

Forge

### Minecraft version

mc 1.20

### Patchouli version

Patchouli-1.19.4-79-FORGE.jar

### Modloader version

46.0.14

### Modpack info

https://www.curseforge.com/minecraft/modpacks/minecolonies-dimensional-adventure

### The latest.log file

https://mclo.gs/nAakQmJ  <-- Latest.log

### Issue description

latest version of rune craft is also downloading the 1.19.4 version of patchouli which causes the mod to crash. as well as just loading patchouli itself is also causing a crash which is kinda as expected seeing as its being forced to load into 1.20 instead of 1.19.4. just figured Id give you a heads up about this and I will also be reporting this issue to the author of rune craft as well.

![patchouli](https://github.com/VazkiiMods/Patchouli/assets/27385258/fb9d6f94-a2ad-49e5-917c-55ae9c0ec828)

[crash report](https://mclo.gs/CZeYekv)

[debug](https://mclo.gs/RyEriGS)

[launcher_log](https://mclo.gs/0NqcMCY)

**Comment by Devilswarchild** [comment]
this is also happening for 1.20.1 albeit not as specific. just giving an exit code 1 on 1.20.1

**Comment by williewillus** [comment]
Patchouli isn't out for 1.20 yet. Please be patient

**Comment by Devilswarchild** [comment]
Well i am being patient but you might wanna let the mod author of rune
craft know that,  bc his mod on 1.20.x is using it as it currently is
