### ISSUE TITLE
forge Server patchouli not working

### ISSUE THREAD

**Issue by warlordkiyan** [VazkiiMods/Patchouli#663]
### Mod loader

Forge

### Minecraft version

1.19.4

### Patchouli version

1.19.4-79

### Modloader version

forge 45.1.0

### The latest.log file

https://gist.github.com/warlordkiyan/96f781521ff338ac4bb13f60e97689c6

### Issue description

i started a minecraft server with patchouli because some mods uses patchouli to help give information about items in the mod but when i try to connect an error shows up 
![image](https://github.com/VazkiiMods/Patchouli/assets/100682446/8876de23-5cd3-43bd-a1d4-66aa5013df29)
single player works fine but connecting  to the server isnt

**Comment by Talia-12** [comment]
I'm having the same issue on 1.20.1, after investigating for a bit I think that the issue is with the following from BookRecipeSerializer:
```
  public @NotNull U fromNetwork(@NotNull ResourceLocation id, @NotNull FriendlyByteBuf buf) {
      T recipe = this.compose().fromNetwork(id, buf);
      return (Recipe)this.converter().apply(recipe, (Object)null);
  }
```
passing null into the converter is breaking assumptions later on, it should be (I'm pretty sure) the ResourceLocation outputBook.

**Comment by michaelortnerit** [comment]
Same Error. Have to remove the mod and then it was working to join the server. It is the 1.20.1 version too.

**Comment by CDAGaming** [comment]
Can report the same issue here too, with the 1.20.1 port that was pushed to CurseForge today. Had to advise my users to remove the mod in the meantime.

**Comment by williewillus** [comment]
@Talia-12 That null was explicitly placed there by https://github.com/VazkiiMods/Patchouli/commit/9b3ac177d0f117a3eb76046ec8851b992ea02605

@Hubry do you remember why this was done?

**Comment by williewillus** [comment]
Oh actually, I see the bug. The code shifted around in 1.19 I believe, will fix.

**Comment by williewillus** [comment]
a82e9f41b95475d134b70b4ba42cb61275008f06
will release a 1.19 backport shortly
