### ISSUE TITLE
Fabric Crash caused by patchouli

### ISSUE THREAD

**Issue by GRKTheGreat** [VazkiiMods/Patchouli#664]
### Mod loader

Forge

### Minecraft version

1.19.4

### Patchouli version

Patchouli-1.19.3-79-FABRIC.jar

### Modloader version

fabric 0.14.21

### Modpack info

Custome

### The latest.log file

https://mclo.gs/YfxJKNy

### Issue description

This version crashes my game...

### Steps to reproduce

download the mod and a few well known mods that use it. Also a lot of performance mods.

### Other information

This mod has been one of the most unstable for me... Now whenever i download fabric 1.19.4 mods i need to make sure this mod is not auto downloaded.

**Comment by williewillus** [comment]
1.19.3 and 1.19.4 are not compatible with each other (blame Mojang).Update the mod or tell your mod pack author to update it (and maybe to test their pack before releasing it)GRKTheGreat ***@***.***> 於 2023年6月22日 23:16 寫道：
Mod loader
Forge
Minecraft version
1.19.4
Patchouli version
Patchouli-1.19.3-79-FABRIC.jar
Modloader version
fabric 0.14.21
Modpack info
Custome
The latest.log file
https://mclo.gs/YfxJKNy
Issue description
This version crashes my game...
Steps to reproduce
download the mod and a few well known mods that use it. Also a lot of performance mods.
Other information
This mod has been one of the most unstable for me... Now whenever i download fabric 1.19.4 mods i need to make sure this mod is not auto downloaded.
