### ISSUE TITLE
Chinese cannot be loaded properly

### ISSUE THREAD

**Issue by Js23333** [VazkiiMods/Patchouli#667]
### Mod loader

Forge

### Minecraft version

1.20.1

### Patchouli version

Patchouli-1.20.1-80-FORGE-20230623.045847-5

### Modloader version

forge 47.0.35

### The latest.log file

https://gist.github.com/Js23333/b82512b74db63ba019b549a7911fa97c

### Issue description

Chinese does not load, but English can load, I think this is an undiscovered bug.Although the Patchouli I used is not the latest version, I found this bug in the latest version

**Comment by williewillus** [comment]
please try again with the latest snapshot and let me know if it works

**Comment by Js23333** [comment]
The latest version no longer has this problem

**Comment by Crossmax14** [comment]
> The latest version no longer has this problem

@Js23333 Hello. I have a request, could you share the .jar file of your build? 
The situation looks like I tried to build the project, but it didn’t work out for me, I am not a Java programmer, and I really want to try the 1.20.1 version in my assembly. Could you send me this file in any way convenient for you? Link to the cloud, or as an attached file in an email (or etc). Here is my email: maximpid@gmail.com, I have other possible ways of contact on my website, which is in my GitHub profile.

**Comment by williewillus** [comment]
Maksym Pidobid ***@***.***> writes:

>> The latest version no longer has this problem
>
> @Js23333 Hello. I have a request, could you share the .jar file of your build? 
> The situation looks like I tried to build the project, but it didn’t work out for me, I am
> not a Java programmer, and I really want to try the 1.20.1 version in my assembly. Could
> you send me this file in any way convenient for you? Link to the cloud, or as an attached
> file in an email (or etc). Here is my email: ***@***.***, I have other possible
> ways of contact on my website, which is in my GitHub profile.

Please do NOT share random JAR files around compiled from trunk. These
are NOT ready for release and are extremely unsafe. Anyone sending a
random JAR file could have infected or tampered with it. Just be
patient. Please.

It's a block game. You can survive a few more days without a book mod
for a block game.

**Comment by Crossmax14** [comment]
Okay then
