### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by TheeMrCheeky** [VazkiiMods/Patchouli#669]
### Mod loader

Forge

### Minecraft version

1.20.1

### Patchouli version

Patchouli-1.19.4-79-FORGE

### Modloader version

47.1.0

### The latest.log file

https://gist.github.com/TheeMrCheeky/88549a2b79e349893f30ea6bb28deb20

### Issue description

[crash-2023-07-08_09.10.00-client.txt](https://github.com/VazkiiMods/Patchouli/files/11990722/crash-2023-07-08_09.10.00-client.txt)

**Comment by williewillus** [comment]
Patchouli 1.20 is not out yet. Please at least look at the version of the mod you're trying to run before running it...

**Comment by TheeMrCheeky** [comment]
Where as I get what you are saying... I didn't download it separately it may of been a mod that requires it that made it auto downloaded it
