### ISSUE TITLE
Cannot start on Minecraft 1.20

### ISSUE THREAD

**Issue by ChaoticUltimateJ** [VazkiiMods/Patchouli#670]
### Mod loader

Forge

### Minecraft version

1.20

### Patchouli version

1.20.1-80

### Modloader version

Forge 46.0.14

(version number added after posting because I'm an idiot)

### The latest.log file

https://pastebin.com/qLy4438E

### Issue description

I installed it because it was a dependancy for another mod that runs in 1.20,
![image_2023-07-10_185515157](https://github.com/VazkiiMods/Patchouli/assets/76010200/31d30035-d44b-4e72-971f-25a1af679474)
appeared in my Minecraft window, I close the game, open it again, it's still there. The mod that I wanted to use is called [Alchemestry](https://www.curseforge.com/minecraft/mc-mods/alchemistry). I made sure to download the forge version of both mods and all of it's dependencies

### Steps to reproduce

1. Install minecraft 1.20 and forge
2. place mod in mods folder
3. ????
4. profit?

### Other information

Other mods I have installed are

- [Alchemestry](https://www.curseforge.com/minecraft/mc-mods/alchemistry)
- [Industrial Revolution](https://www.curseforge.com/minecraft/mc-mods/industrial-revolution)
- [ChemLib](https://www.curseforge.com/minecraft/mc-mods/chemlib)

**Comment by ChaoticUltimateJ** [comment]
I don't know how to view which version of forge I have but if it helps here's a screenshot of it in my mods section in minecraft: 
![image_2023-07-10_191929970](https://github.com/VazkiiMods/Patchouli/assets/76010200/e31004d9-0f4e-461e-9252-8bcdcd01187a)

**Comment by williewillus** [comment]
Patchouli is targeting 1.20.1 and above (Forge 47.x.x and above). You have 1.20 and Forge 46.x.x.

**Comment by williewillus** [comment]
Tell whatever mod that's requiring Patchouli that they should probably check their deps before blindly releasing things. Patchouli 1.20.1 just released yesterday, so for weeks they've been declaring a broken dependency.

**Comment by CDAGaming** [comment]
@williewillus On the topic of this:
`[11.07 11:30:53] [Server] 	Mod ID'forge', Requested by: 'patchouli', Expected range: '[47.1.1,)', Actual version: '47.1.0'`

Why on earth is thus using .1 rather then .0
.1 only contains helper functions that I very highly doubt Patchouli uses or needs, while 47.1.0 is the recommended version of Forge most servers are currently on.
