### ISSUE TITLE
Games crashes while loading the world

### ISSUE THREAD

**Issue by Cape-City** [VazkiiMods/Patchouli#672]
### Mod loader

Fabric

### Minecraft version

1.19.4

### Patchouli version

Patchouli-1.19.4-79.1-FABRIC.jar

### Modloader version

Fabric: Loader 0.14.21 - fabric-api-0.85.0+1.19.4.jar

### The latest.log file

https://gist.github.com/Cape-City/5e1a16124a1daa0b2e948b07567205be

### Issue description

Hi,

if the mod patchouli is active, i can't load any world. Even if i create a new one, the games crahes while loading into it.

Here is also the crashlog:

https://gist.github.com/Cape-City/a63e09a63501f678b98572d5f027c66c

### Steps to reproduce

Just have the 2 mods active:

Paladin's Furniture
UnlikePaladin
paladin-furniture-mod-1.1.3-fabric-mc1.19.4.jar

Patchouli (Fabric/Quilt)
williewillus
Patchouli-1.19.4-79.1-FABRIC.jar

**Comment by williewillus** [comment]
In the log:

> java.lang.AbstractMethodError: Receiver class com.unlikepaladin.pfm.compat.fabric.patchouli.FurnitureRecipeProcessor does not define or inherit an implementation of the resolved method 'abstract void setup(net.minecraft.class_1937, vazkii.patchouli.api.IVariableProvider)' of interface vazkii.patchouli.api.IComponentProcessor.

The Patchouli API changed between 1.19.3 and 1.19.4, so this mod needs
to be updated to accommodate.
