### ISSUE TITLE
Patchouli 1.20.1-81 Crashes launching game

### ISSUE THREAD

**Issue by Silvrus** [VazkiiMods/Patchouli#673]
### Mod loader

Forge

### Minecraft version

1.20.1

### Patchouli version

1.20.1-81

### Modloader version

Forge 47.1.0

### Modpack info

Custom Pack

### The latest.log file

https://pastebin.com/TeYWKLVG

### Issue description

Using 1.20.1-80, the game launches without issue. Upgrading to 1.20.1-81 causes the game to crash.

Crash log: https://pastebin.com/s6gPfmqb

**Comment by Vadewolf** [comment]
can confirm it also breaks shaders too from Laser IO and rubidium as well

https://github.com/Direwolf20-MC/LaserIO/issues/190

https://github.com/Asek3/Oculus/issues/413

**Comment by Vadewolf** [comment]
update forge to 47.1.28 it seems to work

**Comment by SiverDX** [comment]
I mean

[15Jul2023 08:08:45.724] [main/ERROR] [net.minecraftforge.fml.loading.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:
	Mod ID: 'forge', Requested by: 'patchouli', Expected range: '[47.1.1,)', Actual version: '47.1.0'

**Comment by williewillus** [comment]
Patchouli 1.20.1-81 does only *two* things over 1.20.1-80:

1. Bumps the minimum required Forge version
2. Fixes a crash related to book loading

No rendering code was changed.
Any crash that looks like it's due to rendering or shaders is not the
problem of Patchouli, and is either a problem with the Forge requirement
increasing or the rendering mods being used.

There's nothing actionable here for us.

**Comment by Vadewolf** [comment]
@williewillus except when this mod is removed then everything works so umm pls explain that

**Comment by SiverDX** [comment]
> @williewillus except when this mod is removed then everything works so umm pls explain that

how about you just check your log to see what the problem is
its most likely that you did not update your (forge) dependency / version, which has been mentioned in this issue multiple times as a solution

**Comment by Vadewolf** [comment]
> > @williewillus except when this mod is removed then everything works so umm pls explain that
> 
> how about you just check your log to see what the problem is its most likely that you did not update your (forge) dependency / version, which has been mentioned in this issue multiple times as a solution

i legit know wat im doing cause i removed patchouli and everything works but if i add it in then im forced to use forge 47.1.28 which isnt supported and my menu screen breaks so its 100% patchouli
