### ISSUE TITLE
Working version for 1.20 ?

### ISSUE THREAD

**Issue by Attemiff** [VazkiiMods/Patchouli#674]
### Describe the feature

I tried using 1.20.1 on my modded world and it crashed because it needed a different java/forge version (47, which I believe is for 1.20.1, not for 1.20) XD

Is there a working 1.20 version or a plan to create it? 

Thanks again, this mod is so useful and helps with so many things!

**Comment by williewillus** [comment]
No, there's no 1.20.0 version planned.
