### ISSUE TITLE
Book Does Not Open

### ISSUE THREAD

**Issue by Multi-Coder-24** [VazkiiMods/Patchouli#676]
### Mod loader

Forge

### Minecraft version

1.20.1

### Patchouli version

1.20.1-81-FORGE

### Modloader version

Forge 

### Modpack info

47.1.21

### The latest.log file

https://gist.github.com/DDX5/c156b6512c0b4d2087e7eda32dc1b637

### Issue description

When following the getting started guide. The book item shows up, however the book cannot be opened

### Steps to reproduce

1. With new IDE loaded and a new mod setup with the dependency follow the getting started guide.
2. Create a new book following the guide and replacing the required information with the corresponding information (mod id, book id)
3. Load world with no entries.
4. Book appears but cannot open

### Other information

https://gist.github.com/DDX5/a89f7a0d815cdd9072a8fadb4e0fc540 This is the current json file

**Comment by williewillus** [comment]
Do you have your other jsons? The dev workspace Forge test books all
load fine.

**Comment by Multi-Coder-24** [comment]
After deleting the run folder and reloading, The issue has resolved. I'm guessing that a file somewhere got corrupted
