### ISSUE TITLE
1.20 support?

### ISSUE THREAD

**Issue by FAKHORII** [VazkiiMods/Patchouli#677]
### Describe the feature

whish this was also for 1.20 and not just straight to 1.20.1

**Comment by williewillus** [comment]
We don't have the resources to do that. Sorry.On Jul 17, 2023 12:53, FAKHORI ***@***.***> wrote:
Describe the feature
whish this was also for 1.20 and not just straight to 1.20.1
Additional context
No response

**Comment by FAKHORII** [comment]
Appreciate the care, wish u the best <3

**Comment by sykesgabri** [comment]
I'd just like to ask what you mean by this. My server's running on 1.20 and has complex mods that rely on Patchouli for ingame documentation, so it's extremely annoying that there's a 1.19.4 and a 1.20.1 version, but no 1.20 version. Yes, I have tried running both on my server, and both caused a crash on startup due to the versions of the game and the mod not lining up. If I recall correctly 1.20.1 changed nothing from 1.20 other than a few minor bugfixes, so I don't see why making a version of Patchouli for 1.20 would be so difficult.

> We don't have the resources to do that. Sorry.On Jul 17, 2023 12:53, FAKHORI ***@***.***> wrote: Describe the feature whish this was also for 1.20 and not just straight to 1.20.1 Additional context No response —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by williewillus** [comment]
Gabriel Sykes ***@***.***> writes:

> I'd just like to ask what you mean by this. My server's running on 1.20 and has complex
> mods that rely on Patchouli for ingame documentation, so it's extremely annoying that
> there's a 1.19.4 and a 1.20.1 version, but no 1.20 version. Yes, I have tried running both
> on my server, and both caused a crash on startup due to the versions of the game and the
> mod not lining up.

Yes, 1.20.0 and 1.20.1 are not compatible.

> If I recall correctly 1.20.1 changed nothing from 1.20 other than a few
> minor bugfixes, so I don't see why making a version of Patchouli for 1.20 would be so
> difficult.
>

1.20.0 lived a grand total of 5 days before being superseded by
1.20.1. It's not worth the effort forking a 1.20.0 branch, applying all
the appropriate changes, releasing it, and committing to some sort of
support for it, especially given how vanishingly little my free time and
energy for modding is getting.

**Comment by FAKHORII** [comment]
Yo bro, Just make this issue closed, u don't have to listen to us, u do what u WANT, doesn't really matter what WE want
have a good day

**Comment by quat1024** [comment]
update the rest of the mods on your server to 1.20.1
