### ISSUE TITLE
Forge 47.1.1 Dependency 

### ISSUE THREAD

**Issue by Tabarian** [VazkiiMods/Patchouli#678]
### Mod loader

Forge

### Minecraft version

1.20.1

### Patchouli version

1.20.1-81

### Modloader version

Forge 47.1.0

### The latest.log file

https://pastebin.com/rRLqzBS6

### Issue description

Mod ID: 'forge', Requested by: 'patchouli', Expected range: '[47.1.1,)', Actual version: '47.1.0'

I can't find any downloads for a version 47.1.1 on the Curseforge release blog, not sure it exists yet

### Steps to reproduce

1. Have the mentioned version of patchouli in the mod file for a locally hosted server
2. attempt to run run.bat to start server

**Comment by williewillus** [comment]
They're here: https://files.minecraftforge.net/net/minecraftforge/forge/
