### ISSUE TITLE
Chiseled Bookshelf support

### ISSUE THREAD

**Issue by ObieTheWitchBoy** [VazkiiMods/Patchouli#680]
### Describe the feature

With the addition of Chiseled Bookshelves in 1.20, it makes logical sense to be able to store mods' guidebooks generated with Patchouli in them as well as vanilla book items.

**Comment by williewillus** [comment]
ObieTheWitchBoy ***@***.***> writes:

> ### Describe the feature
>
> With the addition of Chiseled Bookshelves in 1.20, it makes logical sense to be able to store mods' guidebooks generated with Patchouli in them as well as vanilla book items. 
>
> ### Additional context
>
> _No response_

Are you having trouble doing so? Book items generated by Patchouli can
already go into chiseled bookshelves. Mods that use their own book items
instead of Patchouli's will have to add them to the `bookshelf_books`
item tag.

**Comment by ObieTheWitchBoy** [comment]
I thought I was, but I went back and double checked and the books I was having trouble with aren't Patchouli books, and the patchouli ones work fine! Sorry, my mistake! Thanks for the info though!
