### ISSUE TITLE
Crash every time

### ISSUE THREAD

**Issue by Ozakiel** [VazkiiMods/Patchouli#684]
### Mod loader

Forge

### Minecraft version

1.19.4

### Patchouli version

79.1

### Modloader version

latest forge on 1.19.4

### The latest.log file

The game crashed whilst unexpected error Error: java.lang.AbstractMethodError: Receiver class com.unlikepaladin.pfm.compat.forge.patchouli.FurnitureRecipeProcessor does not define or inherit an implementation of the resolved method 'abstract void setup(net.minecraft.world.level.Level, vazkii.patchouli.api.IVariableProvider)' of interface vazkii.patchouli.api.IComponentProcessor.

### Issue description

Game crashing every time : The game crashed whilst unexpected error
Error: java.lang.AbstractMethodError: Receiver class com.unlikepaladin.pfm.compat.forge.patchouli.FurnitureRecipeProcessor does not define or inherit an implementation of the resolved method 'abstract void setup(net.minecraft.world.level.Level, vazkii.patchouli.api.IVariableProvider)' of interface vazkii.patchouli.api.IComponentProcessor.

**Comment by williewillus** [comment]
Ozakiel ***@***.***> writes:

> ### Mod loader
>
> Forge
>
> ### Minecraft version
>
> 1.19.4
>
> ### Patchouli version
>
> 79.1
>
> ### Modloader version
>
> latest forge on 1.19.4
>
> ### Modpack info
>
> _No response_
>
> ### The latest.log file
>
> The game crashed whilst unexpected error Error: java.lang.AbstractMethodError: Receiver
> class com.unlikepaladin.pfm.compat.forge.patchouli.FurnitureRecipeProcessor does not
> define or inherit an implementation of the resolved method 'abstract void
> setup(net.minecraft.world.level.Level, vazkii.patchouli.api.IVariableProvider)' of
> interface vazkii.patchouli.api.IComponentProcessor.
>

Whichever mod is `com.unlikepaladin.pfm` needs to update their Patchouli
compatibility. The signature of IComponenetProcessor changed in 1.19.4.

> ### Issue description
>
> Game crashing every time : The game crashed whilst unexpected error
> Error: java.lang.AbstractMethodError: Receiver class
> com.unlikepaladin.pfm.compat.forge.patchouli.FurnitureRecipeProcessor does not define or
> inherit an implementation of the resolved method 'abstract void
> setup(net.minecraft.world.level.Level, vazkii.patchouli.api.IVariableProvider)' of
> interface vazkii.patchouli.api.IComponentProcessor.
>
> ### Steps to reproduce
>
> _No response_
>
> ### Other information
>
> _No response_

**Comment by williewillus** [comment]
^
