### ISSUE TITLE
crash everytime when opening skyfactory 4

### ISSUE THREAD

**Issue by cyberbeastisdumb6** [VazkiiMods/Patchouli#686]
### Mod loader

Forge

### Minecraft version

1.12.2

### Patchouli version

1.12.2-1.0-20

### Modloader version

Forge 14.23.5.2860

### Modpack info

https://www.curseforge.com/minecraft/modpacks/skyfactory-4

### The latest.log file

https://pastebin.com/PYtEPPQZ

### Issue description

everytime i launch skyfactory 4 it crashes idk why but yes it does

ram: 4gb allocated, 16gb (4gb physical, 12gb pagefile)

**Comment by williewillus** [comment]
1.12 isn't supported anymore, sorry.
One thing it could be is that your persistent data got corrupted. Delete `.minecraft/patchouli_data.json` (from your global .minecraft, not the instance specific one) and retry. Otherwise don't know what's up.

**Comment by cyberbeastisdumb6** [comment]
aaa i get it its because of that data file is deleted soon ill fix this and update this
