### ISSUE TITLE
Mod ID: 'forge', Requested by: 'patchouli', Expected range: '[47.1.1,)', Actual version: '47.0.1'

### ISSUE THREAD

**Issue by Sl1ckThread** [VazkiiMods/Patchouli#693]
### Mod loader

Forge

### Minecraft version

1.20.1

### Patchouli version

Patchouli-1.20.1-81-FORGE

### Modloader version

Forge: 47.0.1

### The latest.log file

https://pastebin.com/jrecYePZ

### Issue description

I had installed the latest version of Patchouli but it says the same issue
Mod ID: 'forge', Requested by: 'patchouli', Expected range: '[47.1.1,)', Actual version: '47.0.1'

### Steps to reproduce

1. Installed the mod via curseforge
2. Run the mod in curseforge
3. boot launcher
4. play the game with the forge mod

**Comment by williewillus** [comment]
You need a newer version of Forge, the error message tells you it wants at least 47.1.1.
