### ISSUE TITLE
Console Spam and Loading Lag with Prehistoric Nature (1.12.2)

### ISSUE THREAD

**Issue by EntityIridescent** [VazkiiMods/Patchouli#694]
### Mod loader

Forge

### Minecraft version

1.12.2

### Patchouli version

1.0-23.6

### Modloader version

Forge 14.23.5.2860

### Modpack info

Custom Modpack

### The latest.log file

https://gist.github.com/EntityIridescent/96d94ee38393271707075eb6c75a62ad

### Issue description

The console is spammed with NullPointerExceptions which seem to arise from Patchouli rendering the Prehistoric Nature entities. This also increases the amount of loading time of the pack in general, and the latest log file ends out around 15MB. The pack has already been tested without Prehistoric Nature or Patchouli, and it runs fine. 

### Steps to reproduce

1. Load Prehistoric Nature mods with Patchouli
2. Wait for the pack to begin loading
3. Takes a significant amount of time/computational resources

### Other information

Techguns as well as Millenaire are installed, and are occasionally mentioned in the NullPointerExceptions.

**Comment by williewillus** [comment]
1.12 isn't supported anymore, sorry. As you mentioned, several mods are in the codepath here. Try removing some of them and seeing if it still happens.

The best thing to do is probably just to edit the Prehistoric Nature jar, find the entry json with pages that render the problematic entities, and delete those pages.
