### ISSUE TITLE
NeoForge 1.20.4 support

### ISSUE THREAD

**Issue by Technici4n** [VazkiiMods/Patchouli#717]
### Describe the feature

Hello, could you update the mod for 1.20.4 NeoForge? I'm happy to provide help (or potentially a PR) if needed. Many thanks :)

**Comment by TheCurle** [comment]
I'm willing to chip in and help too, if needed.

**Comment by Mrbysco** [comment]
If there's anything I can do let me know

**Comment by Mrbysco** [comment]
I've made a start https://github.com/VazkiiMods/Patchouli/pull/718
