### ISSUE TITLE
Crash when using patchouli as a mod in dev enviroments

### ISSUE THREAD

**Issue by sveltarne** [VazkiiMods/Patchouli#722]
### Mod loader

Forge

### Minecraft version

1.18.2

### Patchouli version

71.1

### Modloader version

40.2.17

### The latest.log file

https://pastebin.com/h0RWksMx

### Issue description

In an intellij dev enviroment, whenever i drop the patchouli jar into run/mods minecraft does not start up.

**Comment by InterPlay02** [comment]
Use the dependencies field, instead. I am using it on 1.20.1 and it works fine.
I have added this to my gradle.build:
```
minecraft {
    [...]
    runs {
        [...]
        client {
            [...]
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"
        }
    }
}

repositories {
    maven { url 'https://maven.blamejared.com' }
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
    compileOnly fg.deobf("vazkii.patchouli:Patchouli:1.20.1-84-FORGE:api")
    runtimeOnly fg.deobf("vazkii.patchouli:Patchouli:1.20.1-84-FORGE")
}
```

You should try something similiar, but for 1.18.2
