### ISSUE TITLE
Feature Request: allow links to category pages

### ISSUE THREAD

**Issue by desht** [VazkiiMods/Patchouli#90]
While it's possible to link to an entry with ``$(l:category_id/entry_id)``, it would be also be nice to able to link to a top-level category page with ``$(l:category_id)``.

**Comment by copygirl** [comment]
This is pretty old so I hope it's okay if I bump this issue, to let you know I have wanted this feature when I was working on my own guide book.

**Comment by williewillus** [comment]
this was implemented
